### ISSUE TITLE
Add directory sync abilities

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#106]
Originally reported of Google Code with ID 50.

```
Ganeti should not require the user the whole work of distributing the OS
templates and any changes over the whole cluster.

It should take care for itself to distribute os-templates from the master
to the other nodes.

This might be implemented with some command similar to copyfile, that can
also handle directories, e.g. "copydir" or even better "syncdir", so
/srv/ganeti/os can easily (and maybe even regularly, with cron, or so) be
synced to the state of the master node.


```
Originally added on 2008-12-09 12:33:28 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
I respectfully disagree here. We did have this model of operation in previous
versions and it has been show to be less maintainable than the current model.

What do you do when you have an image-based OS (e.g. 4GB size) and you have 50 nodes?
The cost of replicating that from the master node is not trivial.

Rather, we could have a syncdir option, but not as a default (i.e. not always done)
method of operation. Or, why not even just use rsync (given that you can extract the
node list)?

iustin
```
Originally added on 2008-12-09 12:47:03 +0000 UTC.

Changed State: New

**Comment by Ganeti-Issues-Migrator** [comment]
```
You're right, syncing would cause a problem with such large images.

Therefore doing it automatically should be optional for those who know they have only
scripts.

So, my main request would be to add syncing with an explicit command.
And yes, it could be done with rsync, internally, but it should be a ganeti command.
It's basically very much in the line of "copyfile" and "command", but does syncing.
(if ganeti could handle packaged os templates, the copyfile would suffice here...)

Maybe a good task for getting deeper into the codebase when I try to add this myself.

Definitely, this could be scripted somehow with a shell script in combinaytion with
the copyfile and command functionality - putting /srv/ganeti/os in a package on the
master, issuing rm -rf /srv/ganeti/os/* with gnat-clustercommand, copying the file to
all systems, and then unpacking it again with cluster command... just a bit ugly, and
involves even deleting the stuff from the master temporarily.


```
Originally added on 2008-12-09 12:55:05 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
In that sense, providing a way to automatically sync directories, it makes a lot of
sense indeed. Re-titling bug.

iustin
```
Originally added on 2008-12-09 12:58:36 +0000 UTC.

Changed State: Accepted

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2010-03-12 19:39:33 +0000 UTC.

Added to Milestone: Unplanned

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2011-08-05 14:45:42 +0000 UTC.

Removed from Milestone: Unplanned

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2012-10-22 08:57:07 +0000 UTC.

Changed State: Released

**Comment by Ganeti-Issues-Migrator** [comment]
```
Undo wrong status update.
```
Originally added on 2012-10-22 09:00:20 +0000 UTC.

Changed State: Accepted

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-05-03 09:14:51 +0000 UTC.

Added Labels: Priority-Low
Added to Milestone: Release2.9

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-05-08 08:25:29 +0000 UTC.

Added Labels: SmallTask

**Comment by Ganeti-Issues-Migrator** [comment]
```
Move non-critical bugs scheduled for 2.8 or 2.9 to 2.11, as in those versions only critical bug fixes will be integrated.
```
Originally added on 2013-10-30 09:48:16 +0000 UTC.

Added to Milestone: Release2.11
Removed from Milestone: Release2.9

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-12-09 13:57:53 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2015-03-24 12:47:11 +0000 UTC.

Added Labels: Priority-Medium
Removed Labels: Priority-Low
Added to Milestone: Release2.15
Removed from Milestone: Release2.11

**Comment by benjamir** [comment]
IMO this decade old issue should be closed:
Ganeti seems to be dying, or at least suffering from other problems and syncing a directory is something that can be accomplished with tools outside of Ganeti.
(A tree of small files might as well be kept any VCS and cloned/checked out/exported from there.
For large files maybe use a multicast capable tool like:
flamethrower [Debian package, SystemImager related],
mrsync [old source code on GitHub],
murder [uses bittorrent, albeit former main GitHub-repo read-only],
or udpcast [with restrictions]).

Besides I don't see how rsync (without multicast) could scale to anything more than a few machines for large files.

**Comment by iustin** [comment]
Very fair assesment. :+1:
