### ISSUE TITLE
export fails with confusing error when socat is not installed

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#1135]
Originally reported of Google Code with ID 1079.

```
<b>What steps will reproduce the problem?</b>
1. set up a cluster, forget to install 'socat' on all machines
2. export a vm

<b>What is the expected output? What do you see instead?</b>

It will fail with "socat: such file or directory" in the os.log.

It would be good if the export operation checks beforehand if socat is installed (or better even, at configure time).
```
Originally added on 2015-04-28 15:15:23 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Please don't check at configure time! That would turn a documented run dependency into a build dependency for no reason. Also, typically ganeti is build on one machine and used on different (many) machines, so that test wouldn't even help.
```
Originally added on 2015-04-28 15:34:31 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2016-12-20 12:21:22 +0000 UTC.

Changed State: PatchesWelcome
Removed from Milestone: Release2.15

**Comment by rbott** [comment]
I will move forward with this an close the issue. `socat` is an official dependency which is usually implemented as a package dependency by distributions (e.g. Debian does this).

So it should be safe to assume that `socat` is present on the system and not add more code/exception handling.
