### ISSUE TITLE
luxid dies regularly

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#1149]
Originally reported of Google Code with ID 1093.

```
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=785788
```
Originally added on 2015-05-22 08:04:41 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
i could fix this by removing old stale jobs in ganeti by using:

#> rm -f /var/lib/ganeti/queue/job-*
#> service ganeti restart


```
Originally added on 2015-06-26 10:21:58 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Thats not a fix. It may be a workaround (thanks for that) hiding the problem for a while (though it then leaves the questions why ganeti does not clean up old jobs there), but there is a codepath that does lose filehandles somewhere.

```
Originally added on 2015-06-26 12:53:41 +0000 UTC.

**Comment by iustin** [comment]
Closing very old issues. Feel free to reopen if it still happens on 2.16.

**Comment by ribx** [comment]
I encountered these with 2.16.1, after an update from 2.15.2, but I think I also saw them right after an update from earlier versions to 2.15.2.

Sadly I followed the instructions to delete the job queue to fast, and I have no backups for this dev system.
