### ISSUE TITLE
DRBD 8.4 sync does got over 100 MB/s on 10 Gbit/s network

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#1229]
Originally reported of Google Code with ID 1176.

```
What software version are you running? Please provide the output of "gnt-
cluster --version", "gnt-cluster version", and "hspace --version".

Software version: 2.12.4
Internode protocol: 2120000
Configuration format: 2120000
OS api version: 20
Export interface: 0
VCS version: (ganeti) version v2.12.4

gnt-cluster (ganeti v2.12.4) 2.12.4

hspace (ganeti) version v2.12.4
compiled with ghc 7.6
running on linux x86_64

<b>What distribution are you using?</b>

Debian 8.4

<b>What steps will reproduce the problem?</b>
1. init cluster: gnt-cluster init -s x.x.x.x -D drbd:c-max-rate=1024000,resync-rate=1024000,net-custom='--max-buffers 8000 --max-epoch-size 8000' -H xen-pvm:xen_cmd=xl,kernel_path='/boot/vmlinuz-3-xenU',root_path='/dev/xvda1',initrd_path='/boot/initrd-3-xenU' --master-netdev=xen-priv -N link=xen-priv --vg-name=ffzgvg --enabled-disk-templates plain,drbd,ext --ipolicy-disk-templates plain,drbd,ext ganeti.domain.com
2. add a second node: gnt-node add -s y.y.y.y node2.domain.com
3. create a instance with DRBD template: gnt-instance add -o debootstrap+default -t drbd -n node1:node2 -s 5g -B minmem=1024,maxmem=1024 instance1

<b>What is the expected output? What do you see instead?</b>
With a 10 Gbit/s network I expect DRBD to go over a rate of 100 MB/s but for some reason (maybe a DRBD setting that ganeti is enforcing or not correctly setting) it does not go over 100 MB/s.

<b>Please provide any additional information below.</b>

DRBD version: 8.4.3 (api:1/proto:86-101)

I have already mentioned this issue on the google ganeti group: https://groups.google.com/forum/#!topic/ganeti/9X2J9zaH694 and there are a few ideas by Sascha there on what the problem might be and what would need fixing. 
```
Originally added on 2016-05-04 08:18:56 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Thanks for reporting this issue. It sounds more like a DRBD configuration tuning problem. The parameters should be implemented in Ganeti as disussed in the mentioned thread, the defaults probably do not allow achieving max throughput. Please try to be more specific which setting might be missing or needs to be changed.
```
Originally added on 2016-05-04 10:10:56 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Thanks to Viktor's help on the google group we found out that the problem here really is that it is not possible to set dynamic-resync=True as well as c-plan-ahead=0 at the same time in order to fine-tune DRBD synchronisation. Doing so leads to the following error while creating a new instance:

WARNING: Device creation failed
Failure: command execution error:
Can't create block device <DRBD8(hosts=fa17d3b8-e5e5-4675-af34-8d41fb381ae7/4-ccfee5ec-2b0c-4e15-b32f-2293542445d0/4, port=11004, backend=<LogicalVolume(/dev/ffzgvg/6367d27a-5516-4e11-8da2-90f8118f4afc.disk0_data, not visible, size=20480m)>, metadev=<LogicalVolume(/dev/ffzgvg/6367d27a-5516-4e11-8da2-90f8118f4afc.disk0_meta, not visible, size=128m)>, visible as /dev/disk/0, size=20480m)> on node node1.domain.com for instance instance5.domain.com: Error while executing backend function: Can't execute ''A value of 0 for c-plan-ahead disables the dynamic sync speed controller at DRBD level. If you want to disable it, please set the dynamic-resync disk parameter to False.'': not found ([Errno 2] No such file or directory)

More details and discussion can be found on the original google groups post mentioned in the first comment of this issue.
```
Originally added on 2016-05-04 14:29:30 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2016-05-04 14:36:36 +0000 UTC.

Changed State: Accepted

**Comment by Ganeti-Issues-Migrator** [comment]
```
I just want to mention that we successfully used the command below to get full 10GBit/s sync speed on our cluster.

gnt-cluster modify -D drbd:resync-rate=614400,c-max-rate=0,c-min-rate=0,dynamic-resync=False,c-plan-ahead=0,disk-custom='--c-plan-ahead 0'

Important is the "disk-custom='--c-plan-ahead 0'" to disable the DRBD "dynamic resync controller" that is enabled by default since version 8.4.

Hope this helps someone with the same issue.....
```
Originally added on 2016-09-21 16:04:02 +0000 UTC.

**Comment by jasenhn** [comment]
Yous should also tune "net-custom" parameter:

Like this:
 net-custom: --max-buffers 16384 --max-epoch-size 16384

But be carefull with these because you can cause even kernel panics. Also consider to grow kernel parameter vm.min_free_kbytes to 128-256MB.

**Comment by candlerb** [comment]
FYI, I had the same problem: pair of Dell servers, Ubuntu 18.04, SSD, back-to-back 10G NICs, MTU 9000.

I found that drbd initial sync was 40MB/sec regardless of all the different permutations of resync-rate, dynamic-resync etc.  However when a VM was writing data to a synced disk the writes were being replicated at nearly 300MB/sec, so clearly the disk and net throughput was available.

In the end, I found that it was the `net-custom` setting that made the key difference.  Given the following configuration:

```
gnt-cluster modify -D drbd:resync-rate=204800,disk-custom='--c-plan-ahead 0',net-custom='--max-buffers 16384 --max-epoch-size 16384'
```

it happily resyncs at the requested 200MB/sec rate.

Aside: with `net-custom` but not `disk-custom`, data was written at about 90MB/sec - even with other drbd replication settings at defaults, including `c-max-rate: 61440`.

**Comment by candlerb** [comment]
See [forum](https://groups.google.com/forum/#!msg/ganeti/9X2J9zaH694/v9z9tTNgBgAJ;context-place=forum/ganeti) for detailed description of the `c-plan-ahead` issue.

In short: drbd by default now has dynamic resync enabled.  If you want to disable dynamic resync, you should set `c-plan-ahead=0`.

But in ganeti, setting `dynamic-resync=False` doesn't do this; it just disables ganeti from configuring any dynamic resync parameters.

ganeti refuses to let you set `dynamic-resync=True` (required to configure parameters like c-plan-ahead) and `c-plan-ahead=0` (meaning "disable dynamic resync") at the same time.

I think the *intended* behaviour of `dynamic-resync=False` is that it should disable dynamic resync, in which case it should set `c-plan-ahead=0` in drbd.

**Comment by sgsax** [comment]
Sorry to resurrect an old thread. I've been playing with these tuning options this week and am getting up to 320MB/s throughput on disk creation, but when I try a replace-disk operation, throughput is dropped back down to about 250KB/s. If I kill the replace-disk job, shutdown and start the instance, the sync rate goes back up to 320MB/s. This is on an instance with no disk load at all. Why would these operations behave so differently?

I'm running ganeti 2.15.2 and drbd 8.9.10 on debian 9.8. Here's my current cluster modification:
`gnt-cluster modify -D drbd:resync-rate=614400,c-max-rate=0,c-min-rate=0,dynamic-resync=False,c-plan-ahead=0,disk-custom='--c-plan-ahead 0',net-custom='--max-buffers 16384 --max-epoch-size 16384'`

I've also tried adding `--sndbuf-size 1024k --rcvbuf-size 2048k` to the net-custom options per [this forum thread](https://groups.google.com/forum/#!msg/ganeti/9X2J9zaH694/v9z9tTNgBgAJ;context-place=forum/ganeti), which also didn't help.

**Comment by pboguslawski** [comment]
It seems that ganeti 2.15.2-7+deb9u3 (didn't check newer versions) in debian 9 has a bug and does not set ganeti drbd sync settings on secondary drbd device, when replaced with "gnt-instance replace-disks -s" (you can check on secondary with cmd like "drbdsetup show /dev/drbd9" while disk is being replaced).

We've tested that "gnt-instance replace-disks -s" sets stuff from disk-custom param; workarounds that work for us in debian 9 64-bit (examples for 400 MB/s):

newer dynamic controller ([seems better](https://www.linbit.com/en/how-linbit-improved-drbd-sync-rate-logic/) for apps):

`gnt-cluster modify -D drbd:dynamic-resync=True,c-plan-ahead=20,resync-rate=409600,c-max-rate=409600,c-min-rate=4096,c-fill-target=1000000,disk-custom="--c-plan-ahead 20 --resync-rate 409600 --c-max-rate 409600 --c-min-rate 4096 --c-fill-target 1000000",net-custom="--max-buffers 32k --sndbuf-size 1M --rcvbuf-size 2M"`

older "static" way:

`gnt-cluster modify -D drbd:dynamic-resync=False,c-plan-ahead=0,resync-rate=409600,c-max-rate=409600,c-min-rate=4096,c-fill-target=1000000,disk-custom="--c-plan-ahead 0 --resync-rate 409600 --c-max-rate 409600 --c-min-rate 4096 --c-fill-target 1000000",net-custom="--max-buffers 32k --sndbuf-size 1M --rcvbuf-size 2M"`

Not tested for a long time so be careful and test before use :)

Regards,
Paweł

**Comment by rbott** [comment]
As we are getting closer to a 3.0 release, I suppose we should revisit current defaults. From this comment: 
https://github.com/ganeti/ganeti/blob/b1277587e6a12903c144dcf7df9ce605b3756fd6/src/Ganeti/Constants.hs#L4219-L4225
I think we can assume that most parameters are somewhat on par with whatever was suggested around the 8.3 DRBD release.

I have checked the current documentation on [performance](https://docs.linbit.com/docs/users-guide-8.4/#p-performance) and found the following defaults to be recommended:
* net/max-buffers 8000
* net/max-epoch-size 8000
* net/unplug-watermark 16
* net/sndbuf-size 512k (or something up to 2MB) - or "auto tuning" via net/sndbuf-size 0
* the following two settings are supposed to be sane defaults for battery backed RAID storage systems - I am not sure if we should assume this to be a common baseline for all Ganeti users:
  * disk/disk-barrier no;
  * disk/disk-flushes no;

In our own Ganeti setups, we use the above mentioned buffers/epoch-size values when there are only Gigabit Links available. 10GbE Setups use *16.000* for both. On top of that, we use the following settings for resync:
* c-plan-ahead 20
* c-min-rate 10240
* c-max-rate 131072

Does it make sense to introduce the DRBD net settings as separate cluster parameters? Or should we just give the "net-custom" field a default value?

**Comment by rbott** [comment]
#1709 partially addresses this issue, at least from a documentation perspective.

**Comment by rbott** [comment]
I will close this for now as this has been addresses with a documentation update.
