### ISSUE TITLE
Travis-CI and Haskell version/dependencies are broken and fail to build tests

### ISSUE THREAD

**Issue by Morgawr** [ganeti/ganeti#1258]
According to https://travis-ci.org/ganeti/ganeti in the latest build for 2.16, tests are broken on what I assume is an incorrect match of haskell/ghc versions and cabal invocations.

**Comment by Morgawr** [comment]
I'm disabling the travis-CI checks for the moment as they are buggy/broken, on all branches that previously had them enabled.

**Comment by apoikos** [comment]
I've been working on this and have a Travis/Docker build running. I'll open a PR as soon as we're done with the GHC stuff.
