### ISSUE TITLE
MonadCatchIO-transformers is deprecated

### ISSUE THREAD

**Issue by Morgawr** [ganeti/ganeti#1282]
According to https://hackage.haskell.org/package/MonadCatchIO-transformers, this package is deprecated and is replaced by exceptions (https://hackage.haskell.org/package/exceptions) instead.

The package does not seem to be available on Ubuntu (18.04) anymore. This will make it harder to build and package Ganeti in the future.

We should try to move from MonadCatchIO-transformers to exceptions instead.

I haven't looked at the code yet to see how much effort this would be, so that would already be a  good place to start from.

**Comment by Morgawr** [comment]
Looks like this has already been taken care of by @apoikos 
https://github.com/apoikos/ganeti/commit/00515120f97bb306350d96ad15396bd665ed45ec

I've started merging these changes in my local tree @ https://github.com/Morgawr/ganeti/tree/haskell-deps-fix

I'll probably have a pull request ready soon.

**Comment by apoikos** [comment]
Closed via 8c8038510ea363aa81631ae763124356c904d563.
