### ISSUE TITLE
ganeti-kvm-poweroff does not work in debian 9

### ISSUE THREAD

**Issue by pboguslawski** [ganeti/ganeti#1288]
Hi,
ganeti-kvm-poweroff script does not play with debian 9/systemd; after installation with

    /usr/sbin/update-rc.d ganeti-kvm-poweroff defaults

it is not fired on node shutdown. Changing https://github.com/ganeti/ganeti/blob/master/doc/examples/ganeti-kvm-poweroff.initd.in#L8 like this

    -# Default-Start:
    +# Default-Start: 2 3 4 5

works for us.

Regards,
Pawel

**Comment by apoikos** [comment]
Fixed in stable-2.16 with #1343
