### ISSUE TITLE
www.ganeti.org needs a few updates

### ISSUE THREAD

**Issue by dannyman** [ganeti/ganeti#1304]
http://www.ganeti.org/
The public git repository needs to be revised to point here?
The issue tracker link needs to be revised to point here?
Cheers,
-danny

**Comment by ge-fa** [comment]
@dannyman Thanks for reporting, people are aware. We're working on fixing this, and hope this will work out soon. :)

**Comment by rbott** [comment]
Closing this issue as everything has been solved a while ago (after moving to new layout/Github Pages).
