### ISSUE TITLE
Disk hotplugging is broken with QEMU >= 2.8

### ISSUE THREAD

**Issue by apoikos** [ganeti/ganeti#1316]
When hotplugging a disk on a KVM instance, we're using the `blockdev-add` QMP command to register the disk with the hypervisor. The form of the command we're using is unfortunately no longer supported since [QEMU 2.8](https://github.com/qemu/qemu/commit/0153d2f50bc2ad3f41810d838fcf66acbf10f07a). Hot-adding a disk to an instance currently outputs:

```
          Content: [2, message,  - WARNING: Could not hotplug device: Error while executing backend function: kvm: error executing the blockdev-add command: Parameter 'driver' is missing (GenericError):]
```

The `blockdev-add` command was previously regarded experimental and has been marked stable as of QEMU 2.9.

**Comment by mjevans** [comment]
It is marked as stable in 2.9, but my target environment (Debian, current stable) still ships 2.8

https://wiki.qemu.org/ChangeLog/2.9#Block_devices
https://patchwork.kernel.org/patch/9638133/

Based on reading the ganeti design notes as well as the patch notes, the use of named devices may simplify device support in ganeti if QEMU 2.9+ is required (and the data structures are based off of the names).

**Comment by apoikos** [comment]
Note that this seems to have been worked around in 2.16 with b96a2010b5c445d4f25790a23bd022c770f36130. We need to confirm if this is the case.

**Comment by apoikos** [comment]
Confirmed, disk hotplugging seems to work with 2.16.0 and QEMU 3.1. I'm closing this for the time being, we'll revisit it when we decide to completely deprecate the HMP in favor of QMP!
