### ISSUE TITLE
gnt-backup import fails

### ISSUE THREAD

**Issue by cblank2** [ganeti/ganeti#1319]
Hi there,

i'm running ganeti2-2.5.2-1+deb7u2 on debian 7.11 with plain storage on a single server. 

I tried to import a backup (created with gnt-backup export) to have a clone of the original (still running) vm with this command:

gnt-backup import --no-nics --net 0:mac=generate  -t plain --disk 0:size=170G -B memory=20G -n mf2.xxx --src-n=mf2.xxx --src-dir=/var/lib/ganeti/export/neu.xxx www2.xxx

it outputs:

```
Wed Jan 23 15:53:24 2019 * disk 0, vg vg0, name 73f477f6-bf3a-4449-a503-abc3d112454b.disk0
Wed Jan 23 15:53:24 2019 * creating instance disks...
Wed Jan 23 15:53:25 2019 adding instance www2.xxx to cluster config
Wed Jan 23 15:53:25 2019  - INFO: Waiting for instance www2.xxx to sync disks.
Wed Jan 23 15:53:25 2019  - INFO: Instance www2.xxx's disks are in sync.
Wed Jan 23 15:53:25 2019 * running the instance OS import scripts...
Wed Jan 23 15:53:25 2019 Exporting disk/0 from mf2.xxx to mf2.xxx
Wed Jan 23 15:53:28 2019 disk/0 is now listening, starting export
Wed Jan 23 15:53:30 2019 disk/0 is receiving data on mf2.xxx
Wed Jan 23 15:53:30 2019 disk/0 is sending data on mf2.xxx
Wed Jan 23 15:53:35 2019 disk/0 sent 268M, 44.6 MiB/s, 0%, ETA 49m 1s
Wed Jan 23 15:54:36 2019 disk/0 sent 573M, 1.3 MiB/s, 0%, ETA 1d 3h 46m 58s
Wed Jan 23 15:55:37 2019 disk/0 sent 573M, 0.0 MiB/s, 0%
Wed Jan 23 15:56:38 2019 disk/0 sent 573M, 0.0 MiB/s, 0%
...
Thu Jan 24 09:18:41 2019 disk/0 sent 573M, 0.0 MiB/s, 0%
```

(since i tried this a few times yesterday, and aborted this command after a few minutes, i tried to let it run the whole night... but no luck ;-(
so i killed the process "restore" - and this output followed:

```
Thu Jan 24 09:19:42 2019  - WARNING: import 'import-disk0-2019-01-23_15_53_25-DwKZDt' on mf2.xxx failed: Exited with status 1
Thu Jan 24 09:19:42 2019 disk/0 failed to receive data: Exited with status 1 (recent output: BLKRRPART: Invalid argument\nsfdisk: ERROR: sector 0 does not have an msdos signature\n /dev/vg0/73f477f6-bf3a-4449-a503-abc3d112454b.disk0: unrecognized partition table type\nNo partitions found\nBLKRRPART: Invalid argument\nrestore: cannot open /dev/tty: No such device or address\nrestore: ./lost+found: File exists\ndd: dd: writing `standard output': Broken pipe\nsocat: E write(1, 0x7febee5da010, 16384): Broken pipe\nrestore interrupted, continue? [yn] )
Thu Jan 24 09:19:42 2019  - WARNING: Aborting export 'export-disk0-2019-01-23_15_53_29-Ko2ZOy' on mf2.xxx
Thu Jan 24 09:19:42 2019  - WARNING: export 'export-disk0-2019-01-23_15_53_29-Ko2ZOy' on mf2.xxx failed: Exited with status 1
Thu Jan 24 09:19:42 2019 disk/0 failed to send data: Exited with status 1 (recent output: socat: E SSL_write(): Connection reset by peer\ndd: dd: writing `standard output': Broken pipe)
Thu Jan 24 09:19:42 2019  - WARNING: Some disks for instance www2.xxx on node mf2.xxx were not imported successfully
```

yesterday i also tried to import an other backup with the same command (just the src-dir path changed):
```
import --no-nics --net 0:mac=generate -t plain --disk 0:size=170G -B memory=20G -n mf2.xxx --src-n=mf2.xxx --src-dir=/var/lib/ganeti/export/jobs.xxx www2.xxx
```

(since this export is only a few GB it was imported within a few minutes - and no error occurred)

so i tried another backup, which is a 96GB in size - this also worked

so i created a new export from the original vm, with the gnt-backup export command (as it has been run via cronjob, to create the file, which failed first) - the export was created successfully - the import not (this is the above output)

the backup-file, which i'm trying to import, is the biggest one on my server, so i can't test any bigger file - to check, if it fails because of the backup-size. Its 128 GB in size.

so i don't know how to import the file, or how to debug this. I'm not sure, if the file may is corrupted (although i created a new one) or it's simply too large, or - i dont' know.

So my biggest problem is not to import the file (i'll try to dd the original (still running) vm to a new lvm volume or something like this) 
but the fact, i've backups, which are not really reliable - so in case the orginal vm needs to be restored i can't do anything

So, how can this problem be solved or is there a work-around?

**Comment by apoikos** [comment]
By the looks of it, the data transfer stalls. Are the backups on the same node as the import happening? One way to help with debugging is to attach strace to the processes involved (impexpd, socat, dd, restore) and see what kind of activity is going on.

Also, I'm afraid both, 2.5.2 and Debian Wheezy are too old to be supported anymore, so you should upgrade when you get a chance!

**Comment by cblank2** [comment]
Yes the import is on running on the same (only) node, where it was exported and where it was saved on a local disk.

There is no process named impexpd.

strace on the restore process is a very useful hint!
is shows many lines like these (about 20 lines lseek and one line read repeating):
lseek(7, 0, SEEK_CUR)                   = 48072620
read(7, "\3352r\0(\0\10\37sess_r352ura1o55s7j9fanp"..., 1024) = 1024

There is a magento installation in the VM which saves the php-session-files in its own directory, which seems not to be cleared by someone. There are currently 2.200.000 php session files.

Is it really possible, that the restore process of these files takes more than a whole night?

I'll remove them and retry the import with a fresh export without the session files.

Of course, the upgrade is already planned...

**Comment by benjamir** [comment]
Doesn't this look similar to #332 (2.5.2 on CentOS)? That seemed to have been fixed at least with ganeti 2.6.1

**Comment by apoikos** [comment]
> strace on the restore process is a very useful hint!
> is shows many lines like these (about 20 lines lseek and one line read repeating):
> lseek(7, 0, SEEK_CUR) = 48072620
> read(7, "\3352r\0(\0\10\37sess_r352ura1o55s7j9fanp"..., 1024) = 1024
> 
> There is a magento installation in the VM which saves the php-session-files in its own directory, which seems not to be cleared by someone. There are currently 2.200.000 php session files.
> 
> Is it really possible, that the restore process of these files takes more than a whole night?

@cblank2 as `restore` operates on the filesystem level, and ext* filsystems are notoriously slow with big directories, I wouldn't be surprised if the restore process is crawling to death because of this. Awaiting your confirmation, but I suspect there's nothing wrong on Ganeti's side here. Thanks!

**Comment by cblank2** [comment]
Tue Feb 19 11:55:43 2019 disk/0 sent 100.3G, 23.8 MiB/s, 99%, ETA 31s
Tue Feb 19 11:56:18 2019 disk/0 finished sending data
Tue Feb 19 11:56:28 2019 disk/0 finished receiving data

So there's nothing more to say ;-)

Thank you very much!!!

But one question: Why is the import/export using dump/restore? Would a simple dd of a lvm snapshot not be much easier? (and more universal - eg. for other filesystems)
What is the benefit from using dump/restore?

**Comment by apoikos** [comment]
@cblank2: dump/restore operates at the FS level, which guarantees a smaller backup size. `dd` would dump all disk blocks, regardless of whether they are in use by the filesystem or not. Furthermore, dump/restore has the added benefit of being able to restore to a device with *different* size, while `dd`-based backups need to do more work to achieve this.

At any rate, this is OS-provider specific and can be changed at that level.

I guess we can close this :)
