### ISSUE TITLE
QEMU 3.1 compatibility

### ISSUE THREAD

**Issue by apoikos** [ganeti/ganeti#1338]
Debian Buster will be shipping with QEMU 3.1. Currently KVM instances fail to start because we're using `-balloon virtio`, which was removed in 3.1:

```
$ qemu-system-x86_64 -balloon virtio
qemu-system-x86_64: -balloon: invalid option
$ qemu-system-x86_64 --version
QEMU emulator version 3.1.0 (Debian 1:3.1+dfsg-2+b1)
Copyright (c) 2003-2018 Fabrice Bellard and the QEMU Project developers
```

We need to make sure Ganeti works with QEMU 3.1, if possible without using any deprecated features.

**Comment by atta** [comment]
the change have to be in:

https://github.com/ganeti/ganeti/blob/40d7c6a04e1eac2879125093d29c2d1f454456de/lib/hypervisor/hv_kvm/__init__.py#L1286

the new option is:
-device virtio-balloon

**Comment by atta** [comment]
we also sould change the usb-device:
https://github.com/ganeti/ganeti/blob/40d7c6a04e1eac2879125093d29c2d1f454456de/lib/hypervisor/hv_kvm/__init__.py#L1394

the new option is:
-device usb-tablet

**Comment by apoikos** [comment]
Also `-localtime` has been replaced by `-rtc base=localtime`.

**Comment by apoikos** [comment]
`-vnc …,tls` has also been removed and replaced by `-object tls-creds-x509,dir=/path/to/certs,id=tls0,verify-peer=yes -vnc tls-creds=tls0`. Deprecated in 2.5.0, removed in 3.1.0.

**Comment by apoikos** [comment]
`-M` has also been marked as deprecated since 0.15.0 back in 2011 and has been superseded by `-machine`. I guess we should also fix that.

**Comment by atta** [comment]
we can also add the `-nodefaults` option to get rid of the floppy-conroler?

**Comment by apoikos** [comment]
@atta that would change some more things, so it's best left for Ganeti 3.0. The rest should be part of v2.16.1 to ensure that it actually works with modern QEMU versions.

**Comment by dileks** [comment]
Will ganeti/buster Debian package have these changes (current version: 2.16.0-4)?
As a single patch?

Good to know this issue w/ QEMU v3.1 before doing some testing on real hardware.

**Comment by dileks** [comment]
You mean before "Full Freeze" dated 2019-03-12?

[1] https://release.debian.org/buster/freeze_policy.html

**Comment by apoikos** [comment]
@dileks: yes. But there's time even after that and before Buster is out to fix things.

**Comment by parazyd** [comment]
Is anyone also planning to maintain this in Gentoo?

**Comment by atta** [comment]
do we have a "version-variable for qemu" in ganeti 
so we can change the `kvm_cmd.extend ..` only if qemu on the host is > 3 ?

this is the only thin preventing me from creating a new branch to get started on this one.

**Comment by apoikos** [comment]
@atta: I'm already working on this one. We have avoided testing against the version before, I think we can just switch the the new syntax right away.
