### ISSUE TITLE
update the ubuntu PPA for ganeti 2.16.1

### ISSUE THREAD

**Issue by atta** [ganeti/ganeti#1376]
- use debian-salsa to keep track
check https://salsa.debian.org/ganeti-team/ganeti/merge_requests/1 as an example

**Comment by saschalucas** [comment]
generaly the ubuntu PPA should supply as many ganeti versions for as many ubuntu versions as possible.

**Comment by saschalucas** [comment]
This [PPA](https://launchpad.net/~pkg-ganeti-devel/+archive/ubuntu/lts) contains ganeti-2.16.1 (thanks to Apollon, since GanetiCon 2019 Umeå/Sweden). Perhaps this issue can be closed?
