### ISSUE TITLE
gnt-node list shows wrong Sinst count (sinst_cnt)

### ISSUE THREAD

**Issue by the2nd** [ganeti/ganeti#1399]
# Version info.
# gnt-cluster version
Software version: 2.16.1
Internode protocol: 2160000
Configuration format: 2160000
OS api version: 20
Export interface: 0
VCS version: (ganeti) version 2.16.1-9

The command "gnt-node list" shows the wrong "Sinst" count.

Running the following command shows the instances (names) multiple times, once for each disk/drbd device the instance has (in this case 3 disks per instance).

# gnt-node list --no-headers -o sinst_list testnode2 | tr ',' '\n'
instance1
instance1
instance1
instance2
instance2
instance2
instance3
instance3
instance3
instance4
instance4
instance4

It seems like the data is received from luxid at this line https://github.com/ganeti/ganeti/blob/0dfa4d212ae2fc216db0249d5f6e0b4aa22ac059/lib/cli.py#L2035 and i do not have any haskell skills. ¯\_(ツ)_/¯

**Comment by apoikos** [comment]
This is most likely a side-effect of 9825767ad31fa06949cfe6136cc1b9746b1cdfa7, I'll have a look.

**Comment by atta** [comment]
this one can be closed
