### ISSUE TITLE
 (solved) gnt-instance add - failure reasons: FailMem: 6

### ISSUE THREAD

**Issue by gh2O19** [ganeti/ganeti#1400]
Hello,
try to get  Version 2.16.0-5 running on Debian 10 with XEN.

root@XEN1:~# gnt-node list
Node DTotal DFree MTotal MNode MFree Pinst Sinst
xen1  25.0G 25.0G   2.0G  1.8G  126M     0     0
xen2  25.0G 25.0G   2.0G  1.8G  126M     0     0
xen3  25.0G 25.0G   2.0G  1.8G  126M     0     0

root@XEN1:~# gnt-instance add -t drbd -s 5G -B maxmem=512 -o debootstrap+default --no-start inst1 
**Failure: prerequisites not met for this operation:
error type: insufficient_resources, error details:
Can't compute nodes using iallocator 'hail': Request failed: Group default (preferred): No valid allocation solutions, failure reasons: FailMem: 6**

root@XEN1:~# gnt-cluster info | grep -E "lvm|metavg"
  lvm volume group: xenvg
  lvm reserved volumes: (none)
    metavg: xenvg

root@XEN1:~# vgdisplay 
  --- Volume group ---
  VG Name               xenvg
  System ID             
  Format                lvm2
  Metadata Areas        1
  Metadata Sequence No  1
  VG Access             read/write
  VG Status             resizable
  MAX LV                0
  Cur LV                0
  Open LV               0
  Max PV                0
  Cur PV                1
  Act PV                1
  VG Size               <25.00 GiB
  PE Size               4.00 MiB
  Total PE              6399
  Alloc PE / Size       0 / 0   
  Free  PE / Size       6399 / <25.00 GiB
  VG UUID               N9ffu5-0MdA-9W2E-iLCN-NTpR-dZtT-KJM62t

root@XEN1:~# gnt-cluster verify-disks
root@XEN1:~# 

root@XEN1:~# gnt-cluster getmaster
xen1

How can I fix this ?

**Comment by hpanago** [comment]
It looks like your nodes do not have sufficient memory resources for that request.

**Comment by gh2O19** [comment]
Thanks, the NODEs have 2GB RAM.
What is the minimum RAM for a NODE to create one instance ?

**Comment by gh2O19** [comment]
Tryed it with 4G RAM on each node.
But the same error:

root@XEN1:~# gnt-node list
Node DTotal DFree MTotal MNode MFree Pinst Sinst
xen1  25.0G 25.0G   4.0G  3.8G  128M     0     0
xen2  25.0G 25.0G   4.0G  3.8G  128M     0     0
xen3  25.0G 25.0G   4.0G  3.8G  128M     0     0

root@XEN1:~# gnt-instance add -t drbd -s 5G -B maxmem=512 -o debootstrap+default --no-start inst1 
Failure: prerequisites not met for this operation:
error type: insufficient_resources, error details:
Can't compute nodes using iallocator 'hail': Request failed: Group default (preferred): No valid allocation solutions, failure reasons: FailMem: 6

**Comment by bpfoley** [comment]
On Fri, 4 Oct 2019 at 07:19, gh2O19 <notifications@github.com> wrote:

> Tryed it with 4G RAM on each node.
> But the same error:
>
> root@XEN1:~# gnt-node list
> Node DTotal DFree MTotal MNode MFree Pinst Sinst
> xen1 25.0G 25.0G 4.0G 3.8G 128M 0 0
> xen2 25.0G 25.0G 4.0G 3.8G 128M 0 0
> xen3 25.0G 25.0G 4.0G 3.8G 128M 0 0
>
> root@XEN1:~# gnt-instance add -t drbd -s 5G -B maxmem=512 -o
> debootstrap+default --no-start inst1
> Failure: prerequisites not met for this operation:
> error type: insufficient_resources, error details:
> Can't compute nodes using iallocator 'hail': Request failed: Group default
> (preferred): No valid allocation solutions, failure reasons: FailMem: 6
>

The problem is that Ganeti sees 128M free on your nodes. So that's the max
you can allocate to an instance. If you're using Xen, you need to restrict
the amount of memory for dom0, so that MFree shows 1-2G free.

regards,
iustin

**Comment by gh2O19** [comment]
Thank you so much iustin

on each Node:

vi /etc/default/grub.d/xen.cfg

Thank you so much.... one step forward

GRUB_CMDLINE_XEN="nomodeset dom0_mem=640M,max:640M"

update-grub
reboot


root@XEN1:~# gnt-node list
Node DTotal DFree MTotal MNode MFree Pinst Sinst
xen1  25.0G 25.0G   4.0G  640M  3.3G     0     0
xen2  25.0G 25.0G   4.0G  640M  3.3G     0     0
xen3  25.0G 25.0G   4.0G  640M  3.3G     0     0


root@XEN1:~# gnt-instance add -t drbd -s 5G -B maxmem=512 -o debootstrap+default --no-start inst1 
Fri Oct  4 11:14:35 2019  - INFO: Selected nodes for instance inst1 via iallocator hail: xen1, xen2
Failure: command execution error:
Hypervisor parameter validation failed on node xen1: Parameter 'kernel_path' fails validation: not found or not a file (current value: '/boot/vmlinuz-3-xenU')


root@XEN1:~# ls -la /boot/
total 39919
drwxr-xr-x  4 root root     1024 Oct  1 10:27 .
drwxr-xr-x 18 root root     4096 Oct  1 10:16 ..
-rw-r--r--  1 root root   206243 Sep 20 12:51 config-4.19.0-6-amd64
drwxr-xr-x  5 root root     1024 Oct  4 11:12 grub
-rw-r--r--  1 root root 28024735 Oct  1 10:18 initrd.img-4.19.0-6-amd64
drwx------  2 root root    12288 Oct  1 10:13 lost+found
-rw-r--r--  1 root root  3409486 Sep 20 12:51 System.map-4.19.0-6-amd64
-rw-r--r--  1 root root  5262576 Sep 20 12:51 vmlinuz-4.19.0-6-amd64
-rw-r--r--  1 root root     1321 Jun 22 11:15 xen-4.11-amd64.config
-rw-r--r--  1 root root  2670214 Jun 22 11:15 xen-4.11-amd64.efi
-rw-r--r--  1 root root  1113120 Jun 22 11:15 xen-4.11-amd64.gz

**Comment by gh2O19** [comment]
gnt-cluster modify -H xen-pvm:kernel_path=/boot/xen-4.11-amd64.gz,initrd_path=

root@XEN1:~# gnt-instance add -t drbd -s 5G -B maxmem=512 -o debootstrap+default -H kernel_path="none" --no-start inst1 
Unhandled protocol error while talking to the master daemon:
Failed to parse request: SubmitJob: Can't parse value for 'hypervisor': Invalid string value for type Hypervisor: "kernel_path=none"
root@XEN1:~# gnt-instance add -t drbd -s 5G -B maxmem=512 -o debootstrap+default --no-start inst1 
Fri Oct  4 11:26:46 2019  - INFO: Selected nodes for instance inst1 via iallocator hail: xen1, xen2
Fri Oct  4 11:26:47 2019 * creating instance disks...
Fri Oct  4 11:26:52 2019 adding instance inst1 to cluster config
Fri Oct  4 11:26:52 2019 adding disks to cluster config
Fri Oct  4 11:26:52 2019  - INFO: Waiting for instance inst1 to sync disks
Fri Oct  4 11:26:53 2019  - INFO: - device disk/0:  0.50% done, 4m 37s remaining (estimated)

**Comment by gh2O19** [comment]
Thanks for your help!!!
