### ISSUE TITLE
gnt-instance behind a http-proxy ? - Failed getting release file http://deb.debian.org/debian/dists/jessie/Release

### ISSUE THREAD

**Issue by gh2O19** [ganeti/ganeti#1401]
Hi,
where I need to configure the http-proxy that
gnt-instance can download for example debian bootstrap image via proxy ?

root@tst1:~# gnt-instance add -t drbd -s 5G -B maxmem=512 -o debootstrap+default --no-start inst1
Tue Oct  8 08:41:44 2019  - INFO: Selected nodes for instance inst1 via iallocator hail: tst3.net.schuler.de, tst1.net.schuler.de
Tue Oct  8 08:41:45 2019 * creating instance disks...
Tue Oct  8 08:41:49 2019 adding instance inst1 to cluster config
Tue Oct  8 08:41:49 2019 adding disks to cluster config
Tue Oct  8 08:41:50 2019  - INFO: Waiting for instance inst1 to sync disks
Tue Oct  8 08:41:50 2019  - INFO: - device disk/0:  0.40% done, 7m 1s remaining (estimated)
Tue Oct  8 08:42:50 2019  - INFO: - device disk/0: 43.40% done, 1m 18s remaining (estimated)
Tue Oct  8 08:43:50 2019  - INFO: - device disk/0: 86.50% done, 18s remaining (estimated)
Tue Oct  8 08:44:09 2019  - INFO: - device disk/0: 99.40% done, 0s remaining (estimated)
Tue Oct  8 08:44:09 2019  - INFO: - device disk/0: 99.50% done, 0s remaining (estimated)
Tue Oct  8 08:44:09 2019  - INFO: - device disk/0: 99.60% done, 0s remaining (estimated)
Tue Oct  8 08:44:09 2019  - INFO: - device disk/0: 99.70% done, 0s remaining (estimated)
Tue Oct  8 08:44:09 2019  - INFO: - device disk/0: 99.70% done, 0s remaining (estimated)
Tue Oct  8 08:44:09 2019  - INFO: - device disk/0: 99.80% done, 0s remaining (estimated)
Tue Oct  8 08:44:10 2019  - INFO: - device disk/0: 100.00% done, 0s remaining (estimated)
Tue Oct  8 08:44:10 2019  - INFO: Instance inst1's disks are in sync
Tue Oct  8 08:44:10 2019  - INFO: Waiting for instance inst1 to sync disks
Tue Oct  8 08:44:10 2019  - INFO: Instance inst1's disks are in sync
Tue Oct  8 08:44:10 2019 * running the instance OS create scripts...
Failure: command execution error:
Could not add os for instance inst1 on node tst3.net.schuler.de: OS create script failed (exited with exit code 1), last lines in the log file:
Partition #1 contains a ext4 signature.
Re-reading the partition table failed.: Invalid argument
I: Target architecture can be executed
I: Retrieving InRelease 
I: Retrieving Release 
E: Failed getting release file http://deb.debian.org/debian/dists/jessie/Release

Thanks

**Comment by iustin** [comment]
This is a question, not a bug - would be better to ask this on the mailing list.

Please read the README file of ganeti-instance-debootstrap, it explains how to customize the mirror used, how to use a proxy, etc.
