### ISSUE TITLE
Python 3 Migration: Fix various documentation issues and provide up-to-date Dockerfile

### ISSUE THREAD

**Issue by rbott** [ganeti/ganeti#1417]
The current documention files contain various pointers to outdated Python 2 stuff which needs to fixed for Ganeti 3.0.

Furthermore, there is only the older Dockerfile.stretch which is of no use for current tests/builds so we need an updated version.

**Comment by apoikos** [comment]
The Dockerfile is irrelevant and can be safely removed.

**Comment by rbott** [comment]
This has been addressed in #1428 and #1438 

Hence, we can close this issue for now.
