### ISSUE TITLE
Python 3 Migration:  QA testsuite uses NamedTemporaryFile wrong

### ISSUE THREAD

**Issue by rbott** [ganeti/ganeti#1418]
There are a couple of places where the QA testsuite uses `NamedTemporaryFile`. With Python 3, we need to decide whether to use it for text or binary operation (so currently all/most tests which rely on NamedTemporaryFile are broken).

**Comment by rbott** [comment]
I am currently working on a fix and will open a PR as soon as it is working.

**Comment by apoikos** [comment]
Fixed in #1419
