### ISSUE TITLE
gnt-cluster upgrade does not support major version upgrades

### ISSUE THREAD

**Issue by apoikos** [ganeti/ganeti#1423]
As it stands, gnt-cluster upgrade will abort when asked to upgrade to a different major version:

https://github.com/ganeti/ganeti/blob/9d1c128b3135ea0aa17397bc7e1b8d56b542dde5/lib/client/gnt_cluster.py#L2434-L2437

https://github.com/ganeti/ganeti/blob/9d1c128b3135ea0aa17397bc7e1b8d56b542dde5/lib/utils/version.py#L109-L130

This means that `gnt-cluster upgrade --to=3.0` will not work out of the box, and we have to think how we'll address this.

**Comment by rbott** [comment]
Just for clarification: this needs to be most likely addressed in a new 2.16 release as the 2.x code will refuse to upgrade to a new major version. I originally assumed you only need to alter the code in 3.x to allow upgrades _from_ 2.x

However, @apoikos pointed me to the problem that after an installation of ganeti 3, the cluster still runs ganeti 2.x code and the upgrade routines of ganeti 2.x do the relevant steps and change all symlinks to the 3.x binaries/paths at the end.

So we either need support in ganeti 2.15/2.16 for this or we need to ship a tool with ganeti 3 which works around this limitation (sort of 2to3 "ganeti edition")

**Comment by atta** [comment]
somthing like,

MAJOR_UPGRADE_VERSION = (2, 15, 0) ???

https://github.com/ganeti/ganeti/blob/a50e5bb77e20acc9f627ace36cd2c79dade46d7e/lib/utils/version.py#L124

**Comment by rbott** [comment]
This will be / has been addressed in #1449 and #1450

**Comment by saschalucas** [comment]
seems to be solved now: PRs #1449 for 2.16 and #1451 for 3.0
