### ISSUE TITLE
Remove python-simplejson dependency in favor of built-in json

### ISSUE THREAD

**Issue by rbott** [ganeti/ganeti#1427]
Ganeti depends in python-simplejson which has been included as "json" in the standard Python distribution for quite a while now. Since we are officially moving to Python 3 I see no point in using this extra dependency any more.

This comment suggests there seem to have been performance penalties which have been overcome by now as well:
https://github.com/ganeti/ganeti/blob/2aa27a664abec25e626b9f2c9061aa2fba095254/lib/serializer.py#L44-L49

Is there any reason to stick with python-simplejson?

**Comment by apoikos** [comment]
I had a quick shot at it, and it's not a drop-in replacement. The most notable difference is that the built-in JSON module does not handle bytes by default, so at least some of the tests break. But yes, in the long-run we should stick with plain `json`.

**Comment by rbott** [comment]
Thanks for taking a closer look! I will close this issue for now - we can re-open it if needed at a later time.

**Comment by apoikos** [comment]
It's okay, let's keep it open, in case someone wants to work on it.
