### ISSUE TITLE
Powering instance down from within results in ERROR_down rather than USER_down

### ISSUE THREAD

**Issue by ronnyadsetts** [ganeti/ganeti#1440]
Issue reported as suggested by Sascha Lucas.

This is on Debian Buster with ganeti 2.16.0-5 and qemu-system-x86 1:3.1+dfsg-8+deb10u4.

Initially reported by Christian Baumann, Message-Id: <7ad37664-0d85-4361-9d6d-8c489e563b7d@googlegroups.com>.

We sometimes have a need to power down instances from within the instance. This is accomplished in Ganeti using the "user_shutdown" at either the cluster or instance level and with the --user-shutdown cluster option.

This appears to be broken on the above platform. When running a 'poweroff' from within an instance, the instance correctly powers down. The instance status however is reported as ERROR_down. Ganeti watcher then comes along and restarts the instance.

$ sudo gnt-cluster show | grep -E "(shutdown|acpi)"
    acpi: True
    user_shutdown: True
  enabled user shutdown: True
$ sudo gnt-instance show mysql-01.amazing-internet.net | grep -E "(shutdown|acpi)"
    acpi: default (True)
    user_shutdown: default (True)

Thanks.

**Comment by rbott** [comment]
I noticed just now that the user shutdown test was disabled in my nightly QA run. I fixed that et voilà, same error:

```
<<<< 2020-04-11 12:58:19.028683 start [TestInstanceUserDown] Tests user shutdown
 xen-pvm hypervisor is not enabled, skipping test for this hypervisor
 xen-hvm hypervisor is not enabled, skipping test for this hypervisor
 Command: ssh gnt-test01 'gnt-cluster watcher pause 4h'
 Stdout was:
 The watcher is paused until Sat Apr 11 16:58:19 2020.
 Stderr was:
 Warning: Permanently added 'gnt-test01,192.168.122.11' (ECDSA) to the list of known hosts.
 Command: ssh -oEscapeChar=none -oBatchMode=yes -lroot -oStrictHostKeyChecking=no -oClearAllForwardings=yes -oForwardAgent=yes gnt-test01 'gnt-cluster watcher info'
 Warning: Permanently added 'gnt-test01,192.168.122.11' (ECDSA) to the list of known hosts.
 The watcher is paused until Sat Apr 11 16:58:19 2020.
 Command: ssh gnt-test01 'gnt-cluster modify --user-shutdown=true'
 Stderr was:
 Warning: Permanently added 'gnt-test01,192.168.122.11' (ECDSA) to the list of known hosts.
 Command: ssh gnt-test01 'gnt-instance modify -H user_shutdown=true kvm-test-instance01'
 Stdout was:
 Modified instance kvm-test-instance01
  - hv/user_shutdown -> True
 Please don't forget that most parameters take effect only at the next (re)start of the instance initiated by ganeti; restarting from within the instance will not be enough.
 Note that changing hypervisor parameters without performing a restart might lead to a crash while performing a live migration. This will be addressed in future Ganeti versions.
 Stderr was:
 Warning: Permanently added 'gnt-test01,192.168.122.11' (ECDSA) to the list of known hosts.
 Command: ssh gnt-test01 'gnt-instance reboot kvm-test-instance01'
 Stdout was:
 Waiting for job 217 for kvm-test-instance01 ...
 Stderr was:
 Warning: Permanently added 'gnt-test01,192.168.122.11' (ECDSA) to the list of known hosts.
 Command: ssh -oEscapeChar=none -oBatchMode=yes -lroot -oStrictHostKeyChecking=no -oClearAllForwardings=yes -oForwardAgent=yes -oControlPath=/tmp/ganeti-qa-multiplexer.phcimi4o -oControlMaster=no gnt-test01 'gnt-instance list --no-headers --separator=: --units m -o pnode kvm-test-instance01'
 gnt-test01
 Command: ssh gnt-test01 'pkill -f "\-name kvm-test-instance01"'
 Stderr was:
 Warning: Permanently added 'gnt-test01,192.168.122.11' (ECDSA) to the list of known hosts.
 Command: ssh -oEscapeChar=none -oBatchMode=yes -lroot -oStrictHostKeyChecking=no -oClearAllForwardings=yes -oForwardAgent=yes -oControlPath=/tmp/ganeti-qa-multiplexer.phcimi4o -oControlMaster=no gnt-test01 'gnt-instance list --no-headers --separator=: --units m -o status,admin_state,admin_state_source kvm-test-instance01'
 ERROR_down:up:admin
 ---- FAILED [TestInstanceUserDown] Tests user shutdown: 'ERROR_down' == 'USER_down'
 >>>> 2020-04-11 12:58:41.802034 time=0:00:22.773351 [TestInstanceUserDown] Tests user shutdown
```

I'll look into this and see what I can find out.

**Comment by rbott** [comment]
I couldn't really get through to the problem yet, but we might have a rather cosmetic issue here.

`gnt-instance list` shows the instance as ERROR_down:
```
Instance            Hypervisor OS   Primary_node Status     Memory
kvm-test-instance01 kvm        noop gnt-test01   ERROR_down      -
```

whereas `gnt-instance info` shows a correct representation:
```
- Instance name: kvm-test-instance01
  [...]
  State: configured to be up, actual state is user down
```

**Comment by ronnyadsetts** [comment]
Thanks for taking the time to look at this.

I don't see the same as you with an internally-downed instance:

$ sudo gnt-instance list ftp; sudo gnt-instance info ftp | grep "State"
Instance                     Hypervisor OS                  Primary_node                        Status     Memory
ftp kvm        debootstrap+default metropolis ERROR_down      -
  State: configured to be up, actual state is down

So Ganeti sees the instance consistently as down for me from both the 'list' and 'info' gnt-instance commands.

**Comment by apoikos** [comment]
@rbott: can you have a look at what kvmd does/logs during the test run? It's highly likely that this is QMP related...

**Comment by saschalucas** [comment]
> @rbott: can you have a look at what kvmd does/logs during the test run? It's highly likely that this is QMP related...

I have created a test cluster based on v2.16.2 (xenial) and v3.0.0beta1 (focal). I can confirm, that `user_shutdown` is not working in both versions. The logs from kvmd are:
```text
2020-06-16 13:18:09,972264000000 CEST: ganeti-kvmd pid=2594/ThreadId 3 NOTICE ganeti-kvmd daemon startup
2020-06-16 13:18:09,972934000000 CEST: ganeti-kvmd pid=2594/ThreadId 3 INFO User shutdown not enabled, exiting
2020-06-16 13:18:09,973137000000 CEST: ganeti-kvmd pid=2594/ThreadId 3 NOTICE ganeti-kvmd daemon shutdown
```
So it simply does not notice that `user_shutdown=True`. Interestingly it works on xenial package (2.15.2-3)

**Comment by ronnyadsetts** [comment]
I get different results when testing this on v2.16.0 (Debian Buster). the user shutdown appears to be detected. Logs (/var/log/ganeti/kvm-daemon.log on the node running the VM):

2020-06-16 15:48:30,070712241000 BST: ganeti-kvmd pid=23393/ThreadId 31 INFO Detect user shutdown, creating file "/var/run/ganeti/kvm-hypervisor/ctrl/REDACTED.shutdown"
2020-06-16 15:48:30,070971279000 BST: ganeti-kvmd pid=23393/ThreadId 31 INFO Stop monitor "/var/run/ganeti/kvm-hypervisor/ctrl/REDACTED.kvmd"
2020-06-16 15:48:30,072139990000 BST: ganeti-kvmd pid=23393/ThreadId 4 INFO User shutdown file opened "/var/run/ganeti/kvm-hypervisor/ctrl/REDACTED.shutdown"

And then watcher restarts the VM:

2020-06-16 15:50:04,546415699000 BST: ganeti-kvmd pid=23393/ThreadId 4 INFO User shutdown file deleted "/var/run/ganeti/kvm-hypervisor/ctrl/REDACTED.shutdown"
2020-06-16 15:50:07,497886494000 BST: ganeti-kvmd pid=23393/ThreadId 34 INFO Start monitor "/var/run/ganeti/kvm-hypervisor/ctrl/REDACTED.kvmd"

**Comment by saschalucas** [comment]
> I get different results when testing this on v2.16.0 (Debian Buster). the user shutdown appears to be detected. Logs (/var/log/ganeti/kvm-daemon.log on the node running the VM):

Sorry. I totally missed to set `enabled user shutdown` at cluster level. In the first place I assumed, that setting `user_shutdown` at HV level is sufficient. For the moment I don't understand why this are different things. However, correctly set, I got the same results in v3.0.0beta1 (focal):

```text
2020-06-16 17:13:35,636254135000 CEST: ganeti-kvmd pid=8356/ThreadId 8 INFO Start monitor "/var/run/ganeti/kvm-hypervisor/ctrl/test.vm.kvmd"
2020-06-16 17:14:05,944884624000 CEST: ganeti-kvmd pid=8356/ThreadId 8 INFO Detect user shutdown, creating file "/var/run/ganeti/kvm-hypervisor/ctrl/test.vm.shutdown"
2020-06-16 17:14:05,945123161000 CEST: ganeti-kvmd pid=8356/ThreadId 8 INFO Stop monitor "/var/run/ganeti/kvm-hypervisor/ctrl/test.vm.kvmd"
2020-06-16 17:14:05,945252098000 CEST: ganeti-kvmd pid=8356/ThreadId 4 INFO User shutdown file opened "/var/run/ganeti/kvm-hypervisor/ctrl/test.vm.shutdown"
```
So `ganeti-kvmd` seems fine. Before the watcher restarts the instance it is shown as `ERROR_down`in `gnt-instance list`and `gnt-instance info` shows:
```text
- Instance name: test.vm
  UUID: 96652bcb-da26-46e9-b3b4-b23fe39e4279
  Serial number: 19
  Creation time: 2020-06-16 13:39:28
  Modification time: 2020-06-16 17:15:02
  State: configured to be up, actual state is user down
```

More surprise is that v2.16.2 (xenial) works as expected: `gnt-instance list` shows `USER_down` and  `gnt-instance info` shows `configured to be up, actual state is user down`. Seems like there are more differences between v2.16.2 and the debian 2.16-version.

For the moment I got it (mostly) reproduced.

**Comment by saschalucas** [comment]
Just for the record. I have evaluated the following bug matrix (Ganeti versions are latest release tags in git):

| Ganeti/Distro | 3.0/buster | 2.16/buster | 2.16/xenial | 2.16/bionic | 3.0/bionic | 3.0/focal |
|---|---|---|---|---|---|---|
| gnt-instance list | ERROR_down |  ERROR_down | USER_down | USER_down| USER_down | ERROR_down |
| qemu version | 3.1 | 3.1 | 2.5 | 2.11 | 2.11 | 4.2 |

All other information is identical
```text
gnt-instance info: configured to be up, actual state is user down
kvm-daemon.log: Detect user shutdown
```
The first conclusion that comes to my mind is, that no BUG was introduced in Ganeti itself, rather it's a compatibility issue (with qemu?).

My tests were done, by killing the qemu-process like QA run does.

**Comment by saschalucas** [comment]
Looking at the qemu/QMP side I can't find any differences regarding the events at `user_down`:
```json
# bionic (working)
{"timestamp": {"seconds": 1592425792, "microseconds": 331213}, "event": "SHUTDOWN", "data": {"guest": true}}

# buster (broken)
{"timestamp": {"seconds": 1592425977, "microseconds": 458172}, "event": "SHUTDOWN", "data": {"guest": true}}
```
That matches with the observation of `kvm-daemon.log: Detect user shutdown` in both cases. I think, that @apoikos assumption (QMP-related) can be ruled out.

**Comment by iustin** [comment]
So, from the comment about versions, is it correct that basically every QEMU ≥ 3.1 is broken? And only those?

**Comment by rbott** [comment]
> Ganeti/Distro	3.0/buster	2.16/buster	2.16/xenial	2.16/bionic	3.0/bionic	3.0/focal
> gnt-instance list	ERROR_down	ERROR_down	USER_down	USER_down	USER_down	ERROR_down
> qemu version	3.1	3.1	2.5	2.11	2.11	4.2

There could be another angle to ERROR_down / USER_down:

Xenial and Bionic use Haskell 7.10 / 8.0 whereas buster, and focal use 8.4 / 8.8. Maybe something broke with 8.4 (or rather: after 8.0) on the Haskell side?

**Comment by cilq** [comment]
I was able to identify a different behavior of luxid between bionic and buster.
On Bionic the `determineInstanceStatus` in Instance.hs receives a `liveData` Response when running `gnt-instance list` after a vm is in user shutdown. In Buster this function receives `Nothing`.
My Haskell skills are very limited so maybe someone else already has an idea what might be going on. In the meantime I will look into the `genericQuery` function in Query.hs because I think this is where the data should come frome via the `runtime` Variable.
