### ISSUE TITLE
Build broken with Cabal 3

### ISSUE THREAD

**Issue by apoikos** [ganeti/ganeti#1492]
Cabal 3 changed its [APIs](https://github.com/haskell/cabal/pull/6022/files) as well as the [default command behavior](https://www.haskell.org/cabal/users-guide/nix-local-build-overview.html), breaking the build. I've already fixed this, expect a PR soon.

**Comment by iustin** [comment]
I missed this bug, and I started on this. I have now Ganeti working with Cabal 3, the question is just what backwards compat we want before making the patch ready…

**Comment by apoikos** [comment]
Thanks! We still need support with Cabal 1.24+ at this point I'd say. Btw, I'll push my branch somewhere in case you want to cross-check with the work I did.

**Comment by apoikos** [comment]
@iustin: you can also check out https://github.com/apoikos/ganeti/commits/fix/cabal_3.0

**Comment by iustin** [comment]
Your changes are in practice the same as mine (I did the exernalPackageDeps slightly differently, but not much), just better prepared for review. Can you send a pull request?

Note that the network-bsd problem needs to be solved slightly differently, if we want ganeti 3.0 to still work on Buster.

**Comment by apoikos** [comment]
@iustin: opened #1499 without Network.BSD. I suspected that much about Network.BSD but didn't have time to look into it, so feel free to propose a good solution :-)
