### ISSUE TITLE
Build broken with GHC 8.8

### ISSUE THREAD

**Issue by apoikos** [ganeti/ganeti#1493]
Base 4.13.0 completely removed `fail` from the `Monad` class (see [the migration guide](https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/8.8)) and Ganeti currently does not build against GHC 8.8. This should be straightforward to address, expect a PR soon.

**Comment by iustin** [comment]
I missed this bug, and I started on this. I (also) have now Ganeti working with GHC 8.8, the question is just what backwards compat we want before making the patch ready…  As keeping backwards compat with before 8.0 will be very painful, and even 8.0 might be ugly enough.

**Comment by apoikos** [comment]
> I missed this bug, and I started on this. I (also) have now Ganeti working with GHC 8.8, the question is just what backwards compat we want before making the patch ready… As keeping backwards compat with before 8.0 will be very painful, and even 8.0 might be ugly enough.

It's okay, I didn't get a chance to do much. We already support only 8.0+ in ganeti master, so you can count on `MonadFail` being available.

**Comment by iustin** [comment]
OK, docs are unclear, as INSTALL says GHC 7+ :)

The fun part is that after fixing the MonadFail part, there are a few actual other fixes needed that make me wonder how come the code was not issuing warnings before.

Question: why not bump GHC to 8.4? Do we care about oldstable/stretch, or some other distro that doesn't have 8.4?

**Comment by iustin** [comment]
Ansgar made a good point on ganeti-devel that 18.04 LTS compatibility should be kept in mind. That ships 8.0.2, so it does look like 8.0 compat should be kept :)

**Comment by iustin** [comment]
Made progress - it works with 8.8, but now I have to make it work well with older versions too :) so needs a bit more work.

**Comment by iustin** [comment]
Sigh. Now only 8.4 is broken, in tests. Something about the MonadPlus instance not working correctly, but works in 8.0 and 8.8.

I'll give it a rest for a couple of days, tired :)

**Comment by apoikos** [comment]
I think we can close this now that GHC 8.8 support has been released and tested. Thanks @iustin!
