### ISSUE TITLE
rapi-daemon crashes on every request

### ISSUE THREAD

**Issue by mbakke** [ganeti/ganeti#1502]
Any request to the RAPI causes an empty reply and this backtrace with Python 3.8.2:

```
2020-07-14 20:15:42,856: ganeti-rapi pid=2271 INFO 127.0.0.1:33696 GET /2/version HTTP/1.1 404
2020-07-14 20:15:42,856: ganeti-rapi pid=2271 ERROR Error while handling request from 127.0.0.1:33696
Traceback (most recent call last):
  File "/gnu/store/b4mbm4m3m0gmi09xsg3ba5jp2sfx2plq-ganeti-3.0.0beta1-24-g024cc9fa2/lib/python3.8/site-packages/ganeti/http/server.py", line 617, in _IncomingConnection
    self.request_executor(self, self.handler, connection, client_addr)
  File "/gnu/store/b4mbm4m3m0gmi09xsg3ba5jp2sfx2plq-ganeti-3.0.0beta1-24-g024cc9fa2/lib/python3.8/site-packages/ganeti/http/server.py", line 440, in __init__
    self._SendResponse(sock, request_msg, response_msg,
  File "/gnu/store/b4mbm4m3m0gmi09xsg3ba5jp2sfx2plq-ganeti-3.0.0beta1-24-g024cc9fa2/lib/python3.8/site-packages/ganeti/http/server.py", line 472, in _SendResponse
    _HttpServerToClientMessageWriter(sock, req_msg, msg, timeout)
  File "/gnu/store/b4mbm4m3m0gmi09xsg3ba5jp2sfx2plq-ganeti-3.0.0beta1-24-g024cc9fa2/lib/python3.8/site-packages/ganeti/http/server.py", line 134, in __init__
    http.HttpMessageWriter.__init__(self, sock, response_msg, write_timeout)
  File "/gnu/store/b4mbm4m3m0gmi09xsg3ba5jp2sfx2plq-ganeti-3.0.0beta1-24-g024cc9fa2/lib/python3.8/site-packages/ganeti/http/__init__.py", line 735, in __init__
    sent = SocketOperation(sock, SOCKOP_SEND, data, write_timeout)
  File "/gnu/store/b4mbm4m3m0gmi09xsg3ba5jp2sfx2plq-ganeti-3.0.0beta1-24-g024cc9fa2/lib/python3.8/site-packages/ganeti/http/__init__.py", line 418, in SocketOperation
    return sock.send(arg1)
TypeError: a bytes-like object is required, not 'str'
```

This is with SSL disabled as that was causing other problems.

**Comment by iustin** [comment]
The first comment is correct, there's some issue resulting from the migration to Python 3. But on the second one, simply changing the client is not a sane fix; the issue is in the server, not the client. After all, what goes on the wire is bytes, the problem is how the server interprets it. Double-encoding it on the client side won't solve it.

Ideally we'd detect this by putting entire python codebase through mypy, but even on a trivial codebase of ~1K lines of Python, it was a non-trivial undertaking, so I'm not holding my breath for that.

**Comment by iustin** [comment]
Ah sorry, it's not the client, it's also in the server. Don't know then, but maybe dig down if this is a 3.8 issue, or any py3 version?

**Comment by saschalucas** [comment]
ATM I'm unable to reproduce this problem. RAPI works for me on buster/python-3.7.3 and focal/python-3.8.2
```bash
# Cluster=10.10.1.8 Ganeti=https://github.com/ganeti/ganeti:master OS=focal
root@master:~# curl -k https://localhost:5080/2/info
{"software_version": "3.0.0~beta1", ...

# Cluster=10.10.1.3 Ganeti=https://github.com/ganeti/ganeti:master OS=buster
root@master:~# curl -k https://localhost:5080/2/info
{"software_version": "3.0.0~beta1", ...
```

can you please give some more details under which conditions you get this error?

**Comment by mbakke** [comment]
@saschalucas Oh, that's interesting, thanks.  Probably there is something wrong with my packaging for Guix, or an incompatible dependency somewhere.  I'll dig into it.

**Comment by mbakke** [comment]
@saschalucas Does it still work for you with `--no-ssl` on Focal?  I ran the RAPI under [pdb](https://docs.python.org/3/library/pdb.html) (which is really neat) and for the `/2/info` endpoint I can see the response object being passed to [sock.send](https://github.com/ganeti/ganeti/blob/master/lib/http/__init__.py#L418) as a raw string.  Same with the `/version` endpoint.

I doubt the `--no-ssl` case is Guix-specific and will move on to why PyOpenSSL fails.

On a related note, are there .debs available for Ganeti 3?  Then I can install a VM and compare things manually instead of bouncing things off to you.  :-)

**Comment by mbakke** [comment]
Uh, I'm a doofus, the problem was simply that my cURL invokation did not specify `https://`.  When adding that everything is fine.

Apparently the OpenSSL error code when attempting an unencrypted connection is `336130204`.  Perhaps I should send a PR to PyOpenSSL to give a less confusing backtrace in that case. :sweat_smile:

@saschalucas if you can confirm the `--no-ssl` issue I'll open a separate bug report for that.  Closing this for now.

**Comment by saschalucas** [comment]
> @saschalucas if you can confirm the `--no-ssl` issue I'll open a separate bug report for that. Closing this for now.

Yes, I can confirm, that python daemons (rapi, noded) are failing when started with `--no-ssl`. I assume that this may be related to an incomplete python 2to3 migration. I already opened #1508 for this.

> On a related note, are there .debs available for Ganeti 3?

Yes. Please see [https://deb.ganeti.dev/](https://deb.ganeti.dev/).
