### ISSUE TITLE
Flaky config serialization test

### ISSUE THREAD

**Issue by iustin** [ganeti/ganeti#1506]
As seen in https://github.com/ganeti/ganeti/runs/887095914?check_suite_focus=true:

```
2020-07-19T14:49:36.1571390Z ConfigData {configVersion = -9, configCluster = Cluster {clusterRsahostkeypub = "KD\479716", clusterDsahostkeypub = Just
2020-07-19T14:49:36.1577720Z Expected equality, but got mismatch
2020-07-19T14:49:36.1599464Z expected: ConfigData {configVersion = -9, configCluster = Cluster {clusterRsahostkeypub = "KD\479716", clusterDsahostkey
2020-07-19T14:49:47.9545941Z  but got: ConfigData {configVersion = -9, configCluster = Cluster {clusterRsahostkeypub = "KD\479716", clusterDsahostkey
2020-07-19T14:49:47.9552588Z (used seed -3390799639642185379)
```

Full output is too large to inline, attaching.
[8_Haskell tests.txt](https://github.com/ganeti/ganeti/files/4943900/8_Haskell.tests.txt)

**Comment by apoikos** [comment]
It's happening more often, especially  on Buster and Bullseye in the nightly builds. The interesting part is that the reported "mismatch" seems bogus; the current logfiles report a mismatch, but the printed output for "expected" and "got" is the same. So, there's either a bug in the `Eq` instance of `ConfigData`, or there is indeed a mismatch but it's obscured by `show ConfigData`.

Note that what I'm saying does not apply to the logs attached by @iustin; there seems to be an actual mismatch in that case.

**Comment by apoikos** [comment]
The diff in this case is:

```diff
--- /proc/self/fd/16	2020-09-11 23:31:00.214871393 +0300
+++ /proc/self/fd/19	2020-09-11 23:31:00.210871445 +0300
@@ -161,7 +161,7 @@
 00000a00  33 34 5c 31 36 38 5c 45  54 42 35 3b 22 2c 22 5c  |34\168\ETB5;","\|
 00000a10  43 41 4e 5c 39 39 35 35  33 35 5c 4e 41 4b 4a 6e  |CAN\995535\NAKJn|
 00000a20  22 29 2c 28 22 3f 5f 5c  44 43 31 62 5c 32 33 39  |"),("?_\DC1b\239|
-00000a30  5c 31 39 31 5c 31 38 39  5c 26 37 22 2c 22 47 5c  |\191\189\&7","G\|
+00000a30  5c 31 39 31 5c 31 39 30  5c 26 37 22 2c 22 47 5c  |\191\190\&7","G\|
 00000a40  4e 41 4b 5c 39 31 38 33  35 37 71 62 5c 72 5c 35  |NAK\918357qb\r\5|
 00000a50  38 33 36 37 34 22 29 2c  28 22 53 22 2c 22 22 29  |83674"),("S","")|
 00000a60  2c 28 22 55 5c 32 34 31  5c 31 35 32 5c 31 33 30  |,("U\241\152\130|
```
It's a two-byte difference actually, no idea where it could come from...

**Comment by apoikos** [comment]
I managed to reproduce this a couple of times, it's always the same byte sequence, `\239\191\190` that is read back as `\239\191\189`. Let's throw some Python in the mix:
```python
In [17]: b"\xef\xbf\xbe".decode("utf-8")
Out[17]: '\ufffe'
```
U+FFFE is a [special Unicode character](https://en.wikipedia.org/wiki/Specials_(Unicode_block)) in that it is not allowed to appear in Unicode text. I patched the tests to output the serialized form, and indeed the JSON serializer converts U+FFFE to U+FFFD, which is a replacement character used to indicate that something was there that couldn't be encoded in Unicode and which corresponds to `\239\191\189`.

All-in-all, everything seems to work as it should. I don't know how easy it is to tune the various `arbitrary` instances to avoid generating illegal UTF-8 characters, but if we want stable tests, it's something we need to do.

**Comment by iustin** [comment]
This has been an issue starting way way back. The problem is that people extended the Config object without adding custom arbitrary instances - basically the test generates random garbage, whereas the actual code would likely not accept many of the generate fields.

Fixing it is, depending on the depth of the object, relatively easy but it is toil, not something fun to do…
