### ISSUE TITLE
python daemons (rapi, noded) failing when running with --no-ssl

### ISSUE THREAD

**Issue by saschalucas** [ganeti/ganeti#1508]
Steps to reproduce: configure `--no-ssl` in `/etc/default/ganeti` for `RAPI` and `NODED`, restart Ganeti services:

sent test to RAPI:

```bash
root@master:~# curl http://localhost:5080/2/info
curl: (52) Empty reply from server

# content of /var/log/ganeti/rapi-daemon.log
2020-07-20 22:24:31,126: ganeti-rapi pid=7677 ERROR Error while handling request from 127.0.0.1:42484
Traceback (most recent call last):
  File "/usr/local/share/ganeti/3.0/ganeti/http/server.py", line 617, in _IncomingConnection
    self.request_executor(self, self.handler, connection, client_addr)
  File "/usr/local/share/ganeti/3.0/ganeti/http/server.py", line 441, in __init__
    self.WRITE_TIMEOUT)
  File "/usr/local/share/ganeti/3.0/ganeti/http/server.py", line 472, in _SendResponse
    _HttpServerToClientMessageWriter(sock, req_msg, msg, timeout)
  File "/usr/local/share/ganeti/3.0/ganeti/http/server.py", line 134, in __init__
    http.HttpMessageWriter.__init__(self, sock, response_msg, write_timeout)
  File "/usr/local/share/ganeti/3.0/ganeti/http/__init__.py", line 735, in __init__
    sent = SocketOperation(sock, SOCKOP_SEND, data, write_timeout)
  File "/usr/local/share/ganeti/3.0/ganeti/http/__init__.py", line 418, in SocketOperation
    return sock.send(arg1)
TypeError: a bytes-like object is required, not 'str'
```

trigger call to noded:
```bash
root@master:~# gnt-node list

# contents of /var/log/ganeti/node-daemon.log
2020-07-20 22:31:14,315: ganeti-noded pid=7900 ERROR Error while handling request from 10.10.1.2:33110
Traceback (most recent call last):
  File "/usr/local/share/ganeti/3.0/ganeti/http/server.py", line 617, in _IncomingConnection
    self.request_executor(self, self.handler, connection, client_addr)
  File "/usr/local/share/ganeti/3.0/ganeti/server/noded.py", line 156, in __init__
    http.server.HttpServerRequestExecutor.__init__(self, *args, **kwargs)
  File "/usr/local/share/ganeti/3.0/ganeti/http/server.py", line 433, in __init__
    responder(compat.partial(self._ReadRequest, sock, self.READ_TIMEOUT))
  File "/usr/local/share/ganeti/3.0/ganeti/http/server.py", line 300, in __call__
    (request_msg, req_msg_reader) = fn()
  File "/usr/local/share/ganeti/3.0/ganeti/http/server.py", line 458, in _ReadRequest
    reader = _HttpClientToServerMessageReader(sock, msg, timeout)
  File "/usr/local/share/ganeti/3.0/ganeti/http/__init__.py", line 830, in __init__
    buf += data.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 8: invalid start byte

**Comment by iustin** [comment]
I have a suspicion that what happens here is that no-ssl is not really used. I don't have a ganeti cluster handy, what happens if you use curl with https even against no-ssl RAPI daemon?

**Comment by mbakke** [comment]
@iustin On the cURL side I get:

```
$ curl -k https://localhost:5080
curl: (35) gnutls_handshake() failed: The TLS connection was non-properly terminated.
```

And in the RAPI log:

```
  File "/gnu/store/92k9cx0hq2x4hhc4s0bdn1880cg1isi7-ganeti-3.0.0beta1-24-g024cc9fa2/lib/python3.8/site-packages/ganeti/http/__init__.py", line 830, in __init__
    buf += data.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x91 in position 11: invalid start byte
```

FWIW when investigating my brain fart in #1502 I could see rapi-daemon build up a perfectly good response, but it crashed when attempting to send it back over the wire as a string.

**Comment by apoikos** [comment]
@mbakke: this looks like a partial read, where it tries to decode part of a unicode character. Indeed HTTPMessageReader was never written with UTF-8 in mind (and it just worked in Python 2), so it doesn't handle the case where a UTF-8 character is split between two reads. I'll have a look.

**Comment by apoikos** [comment]
Having a second look at the above, here are a couple of comments:

 - `--no-ssl` on the node daemon is useless in real-world situations, as SSL is mandatory for mutual master <-> node authentication.
 - The error in https://github.com/ganeti/ganeti/issues/1508#issuecomment-662436675 is simply because the HTTP server tries to handle the (binary) TLS handshake as text. It fails in a less-than-ideal manner, but the best it would do would be to return a 400 Bad Request.

The only bug we probably need to investigate is the RAPI daemon's failure to respond to plain HTTP, as in the original bug report:

> Steps to reproduce: configure `--no-ssl` in `/etc/default/ganeti` for `RAPI` and `NODED`, restart Ganeti services:
> 
> sent test to RAPI:
> 
> ```shell
> root@master:~# curl http://localhost:5080/2/info
> curl: (52) Empty reply from server
> 
> # content of /var/log/ganeti/rapi-daemon.log
> 2020-07-20 22:24:31,126: ganeti-rapi pid=7677 ERROR Error while handling request from 127.0.0.1:42484
> Traceback (most recent call last):
>   File "/usr/local/share/ganeti/3.0/ganeti/http/server.py", line 617, in _IncomingConnection
>     self.request_executor(self, self.handler, connection, client_addr)
>   File "/usr/local/share/ganeti/3.0/ganeti/http/server.py", line 441, in __init__
>     self.WRITE_TIMEOUT)
>   File "/usr/local/share/ganeti/3.0/ganeti/http/server.py", line 472, in _SendResponse
>     _HttpServerToClientMessageWriter(sock, req_msg, msg, timeout)
>   File "/usr/local/share/ganeti/3.0/ganeti/http/server.py", line 134, in __init__
>     http.HttpMessageWriter.__init__(self, sock, response_msg, write_timeout)
>   File "/usr/local/share/ganeti/3.0/ganeti/http/__init__.py", line 735, in __init__
>     sent = SocketOperation(sock, SOCKOP_SEND, data, write_timeout)
>   File "/usr/local/share/ganeti/3.0/ganeti/http/__init__.py", line 418, in SocketOperation
>     return sock.send(arg1)
> TypeError: a bytes-like object is required, not 'str'
> ```


This is actually a valid scenario if you run RAPI behind a reverse proxy such as nginx or HAProxy,
