### ISSUE TITLE
how do we edit the wiki?

### ISSUE THREAD

**Issue by anarcat** [ganeti/ganeti#1531]
are external contributors welcome to edit the wiki? I am specifically wondering if/how I can add entries to:

https://github.com/ganeti/ganeti/wiki/FAQ#what-are-known-large-and-notable-ganeti-deployments

I know of at least two Ganeti deployment with similar numbers that might be interesting to add in there (koumbit.org, torproject.org, maybe more)...

**Comment by saschalucas** [comment]
Hi,
thanks for your request. Currently the wiki is in push-privilege-edit mode. I've requested a discussion to open it for everyone. I'm awaiting feedback, but looking forward to open the wiki...

Thank, Sascha.

**Comment by ge-fa** [comment]
Any update on this?

**Comment by saschalucas** [comment]
Hi,

It seems that I received no response regarding to open the wiki for everyone[1]. So I'm deciding on my own to open the wiki for everyone (disabled "Restrict editing to users in teams with push access only"). ATM I assume, I can follow upcoming changes, to monitor this experiment.

Sorry for the delay.

[1] https://groups.google.com/g/ganeti-devel/c/zOAoceqmqOU
