### ISSUE TITLE
bridge_vlan_add check for VLAN interface doesn't allow for veth interfaces.

### ISSUE THREAD

**Issue by newellz2** [ganeti/ganeti#1533]
I have a veth pair (ve-gw-0@ve-vm-0) with one end (ve-vm-0) associated with a bridge (br-vm). ve-vm-0 has two VLANs, 1 and 2.
```
~# bridge vlan show dev ve-vm-0
port    vlan ids
ve-vm-0  1 PVID Egress Untagged
         2
```

I created a traditional VLAN interface to handle packets associated with VLAN 2:
```
ip link add link ve-gw-0 name ve-gw-0.2 type vlan id 2
```

When I add instances to VLAN 2 I receive the following error:
````
#/usr/lib/ganeti/net-common 
88:      echo "VLAN ${VID} is in use by interface ${vlan_interface}"
````
Despite the comment below, the veth device (ve-gw-0.2) functions correctly when I disable the check. The tap interfaces added to the bridge are able to communicate with each other and the IP associated with ve-gw-0.2.
```
  # when the VID is in use by traditional VLAN interface, then the
  # tap on the VLAN aware bridge will not receive traffic
```

Here is a small diagram of the setup:
```
                       +--------------------------------+
                       |             br-vm              |
+-------------+        |  +-----------+                 |
|  ve-gw-0    +-----------+  ve-vm-0  |                 |
|             |        |  | VLANs: 1,2|                 |
+------+------+        |  +-----------+                 |
       |               |                                |
       |               +--------------------------------+
+------+------+
|  ve-gw-0.2  |
|             |
+-------------+
```
I'm not sure what's the best way to handle this configuration. Maybe adding a force=True option to the vlan= option to bypass the check?

**Comment by saschalucas** [comment]
Thanks a lot for testing and reporting this issue in that detail. I'll verify this safety check and see, what can be improved.

**Comment by saschalucas** [comment]
Just for recording my thoughts, for later fix of this problem:

* I have verified again, that the vlan-in-use check is necessary/helpfull. consider a note/warning in the man page, too. Not just in the commit message.
* the check can be skipped if the lower device is of type `veth`. The lower device is the 3rd column in `/proc/net/vlan/config`. If `ip -o link show dev $dev type veth` produces exactly one line of output, it is identified as a veth device.
