### ISSUE TITLE
ModuleNotFoundError: No module named 'ganeti'

### ISSUE THREAD

**Issue by sarlacpit** [ganeti/ganeti#1588]
Using Ubuntu 20.04.
Installed version 3.0.1 from Source.
I have built it using the instructions found here (minus Xen bits): https://docs.ganeti.org/docs/ganeti/3.0/html/install.html#installing-the-base-system-and-base-components.

When trying to initiate my cluster for the first time, i get a Python error complaining of no module called ganeti
Not sure where the module is or how see if it's there (my Python skills are to be desired somewhat).

`ganeti-3.0.1# ./scripts/gnt-cluster init --nic-parameters link=br0 --enabled-hypervisors=kvm --vg-name vg_ganeti 
Traceback (most recent call last):
  File "./scripts/gnt-cluster", line 11, in <module>
    import ganeti.client.gnt_cluster as main
ModuleNotFoundError: No module named 'ganeti'`

I am sure I must have missed something but any assistance would be great thanks.

**Comment by sarlacpit** [comment]
Looks like I may have been working from the wrong directory and have issues with my install in regards to the directories.
Should I have been working from /usr/local/share/ganeti/3.0/gnt-cluster

Though the script now does something, if i run my init from there I now get this which also seems to be calling a script from a subdirectory, as in ./usr/ not the root /usr/:

```
root@borg1:/# /usr/local/share/ganeti/3.0/gnt-cluster init --nic-parameters link=br0 --enabled-hypervisors=kvm --vg-name vg_ganeti borg0

Failure: command execution error:
Can't execute '/usr/local/lib/ganeti/daemon-util stop-all': not found ([Errno 2] No such file or directory: '/usr/local/lib/ganeti/daemon-util')

root@borg1:/# /usr/local/lib/ganeti/
3.0/         iallocators/ tools/       
root@borg1:/# /usr/local/lib/ganeti/
3.0/         iallocators/ tools/       
root@borg1:/# /usr/local/lib/ganeti/3.0/usr/local/
bin/  lib/  sbin/ 
root@borg1:/# /usr/local/lib/ganeti/3.0/usr/local/
bin/  lib/  sbin/ 
root@borg1:/# /usr/local/lib/ganeti/3.0/usr/local/lib/ganeti/
daemon-util       kvm-ifup          mon-collector     tools/            vif-ganeti-metad
iallocators/      kvm-ifup-os       net-common        vif-ganeti        xen-ifup-os
root@borg1:/# /usr/local/lib/ganeti/3.0/usr/local/lib/ganeti/
```
Any suggestions would be welcome.
Thanks

**Comment by iustin** [comment]
The question is what arguments you passed to configure? None?

**Comment by sarlacpit** [comment]
Hi iustin,

Thanks for the reply, i ran the following: `./configure --localstatedir=/var --sysconfdir=/etc`

There is a /var/ganeti directory though it is empty:

```ls -al /var/lib/ganeti/
total 8
drwxr-xr-x  2 root root 4096 Mar 30 15:54 .
drwxr-xr-x 46 root root 4096 Mar 31 10:13 ..
```

**Comment by sarlacpit** [comment]
Doh, It looks like I missed a symlinks option...

`./configure --localstatedir=/var --sysconfdir=/etc --enable-symlinks `

Thanks folks!

**Comment by iustin** [comment]
Glad to hear it's solved. Maybe some suggestions to improve documentation? Not sure.

**Comment by sarlacpit** [comment]
Yes and no... whilst there is the flexibility of offering a choice over which directory ti specify (localstatedir & sysconfdir) 
I am not 100% sure of the reason you wouldn't need the symlinks - I tried it blindly hoping it would work. 

So yes to the improvement to the documentation.
and no, the symlinks could possibly be created without having user involvement to specify them.
