### ISSUE TITLE
Instance-Modify makes duplicate checking on argument values

### ISSUE THREAD

**Issue by promasu** [ganeti/ganeti#1598]
Hi there,

I'm currently encountering a bug where the duplication checking for arguments in the ganeti cli (gnt-instance) makes it refuse to change my virtual machine.
In this case I want to change the kernel_args for a VM.

```
~ # gnt-instance modify -H kvm:kernel_args="snd_aloop.enable=1,1,1,1,1 snd_aloop.index=0,1,2,3,4" vm102
Failure: unknown/wrong parameter name 'Duplicate key '1' in option -H'
```

Am I doing something wrong or is this a bug in the Ganeti CLI?

Thanks for your help!

Kind regards.

System-Information:
```
~ # gnt-cluster version
Software version: 2.16.0
Internode protocol: 2160000
Configuration format: 2160000
OS api version: 20
Export interface: 0
VCS version: (ganeti) version 2.16.0-5

~ # cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
```

**Comment by pcworld** [comment]
As you can see in [man gnt-instance](https://docs.ganeti.org/docs/ganeti/2.16/html/man-gnt-instance.html), you need to use backslashes to escape commas:

> ```
> # Pin vCPU 0 to any CPU, vCPU 1 to CPUs 1, 3, 4 or 5, and CPU 2 to
> # CPU 0 (backslashes for escaping the comma)
> gnt-instance modify -H cpu_mask=all:1\\,3-5:0 my-inst
> ```

**Comment by promasu** [comment]
Thank you. That was the problem.
