### ISSUE TITLE
nic hotplug fails when use_guest_agent=True

### ISSUE THREAD

**Issue by glance-** [ganeti/ganeti#1620]
When setting use_guest_agent=True on a kvm instance, ganeti mis-counts the number of used pci devices and fails to hotplug the new nic:
```Wed Nov  3 17:04:22 2021  - INFO: Trying to hotplug device...
Wed Nov  3 17:04:22 2021  - WARNING: Could not hotplug device: Error while executing backend function: kvm: error executing the device_add command: PCI: slot 12 function 0 not available for virtio-net-pci, in use by virtio-serial-pci (GenericError):
```

This is observed on ganeti-3.0 3.0.1-1~bpo10+1 on debian buster and 3.0.1-2 on bullseye.

**Comment by saschalucas** [comment]
Confirmed.

In `_GenerateKVMRuntime`, the QGA part seems the only one setting a PCI slot via `utils.GetFreeSlot`: https://github.com/ganeti/ganeti/blob/3b78ca56a209f0996967fa74ac34b426ecb06ffd/lib/hypervisor/hv_kvm/__init__.py#L1651

During hotplug only NICs and disks count to PCI bus calculation (are available from KVMRuntime): https://github.com/ganeti/ganeti/blob/3b78ca56a209f0996967fa74ac34b426ecb06ffd/lib/hypervisor/hv_kvm/__init__.py#L2199-L2200

Other methods like QMP `query-pci` (via `GetFreePCISlot`) are present in the code, but seems unused? The [design-hotplug](https://github.com/ganeti/ganeti/blob/3b78ca56a209f0996967fa74ac34b426ecb06ffd/doc/design-hotplug.rst) seems to rely on KVMRuntime and not live query. Maybe this is some future code?

The best way ATM seems to remove explicit PCI slot assignment for QGA and let qemu manage it within the first 12 slots (like with spice virtio-serial). This way only NICs and disks would be at slots 12+.
