### ISSUE TITLE
Nic hotplug fails when running qemu chrooted.

### ISSUE THREAD

**Issue by glance-** [ganeti/ganeti#1621]
When running a kvm instance with use_chroot=True and trying to hotplug a nic this happens:
```
Wed Nov  3 17:11:38 2021  - WARNING: Could not hotplug device: Error while executing backend function: kvm: error executing the device_add command: failed to find romfile "efi-virtio.rom" (GenericError):
```

One idea how this could be solved would be using rom_bar=off when hotplugging nic's in a use_chroot=True enviorment. There might be some other way to pass in the rom to the chroot.

**Comment by saschalucas** [comment]
Confirmed.

Don't know if NIC hotplug and chroot ever worked? The man page QEMU.1(1) and `--help` does not show anything regarding `rom_bar` or `rombar`. From previous experience with NICs ROM size mismatch between different qemu versions, I suspect care must be taken to not break live migration and switching rom=on|off in combination with hotplug.
