### ISSUE TITLE
Ganeti 2.12 - CA is unknown

### ISSUE THREAD

**Issue by runtman** [ganeti/ganeti#1627]
Hello, I inherited a really old Ganetic cluster that came to the time of needing it's certificates renewed.

I did the following: `gnt-cluster renew-crypto --new-cluster-certificate --new-node-certificates`

This ended up breaking my 2 node cluster (I know, kill me) to the point where I had to mark the 2nd node as offline.

Now, when I try to readd the node I get the following:

`2021-12-14 16:35:18,327: Unhandled Ganeti error: Given cluster certificate does not match local key
Failure: command execution error:
Command 'ssh -oEscapeChar=none -oHashKnownHosts=no -oGlobalKnownHostsFile=/var/lib/ganeti/known_hosts -oUserKnownHostsFile=/dev/null -oCheckHostIp=no -oPort=22 -oStrictHostKeyChecking=ask -4 root@phx-gnt-2.x.com '/bin/sh -c '\''test -d /usr/local/lib/ganeti/2.12 && ln -s -f -T /usr/local/lib/ganeti/2.12 /etc/ganeti/lib && ln -s -f -T /usr/local/share/ganeti/2.12 /etc/ganeti/share && /usr/local/lib/ganeti/prepare-node-join'\'''' failed: exited with exit code 1`

And if I try to sett offline to no, I get:

`root@phx-gnt-1[A79]:~$ gnt-node modify --offline=no phx-gnt-2.x.com
Tue Dec 14 16:15:57 2021  - INFO: Auto-promoting node to master candidate
Failure: prerequisites not met for this operation:
error type: wrong_state, error details:
Node phx-gnt-2.x.com is being de-offlined but fails to report its version: Error 35: gnutls_handshake() failed: CA is unknown`

I tried the following from the snippet in the below article:

https://groups.google.com/g/ganeti/c/CusPuOWuHYE/m/OKcv12GT5hUJ

But that left me with:

`root@phx-gnt-1[A79]:anthony.cleaves$ python -c 'import pycurl; print pycurl.version'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (gnutls)`

So I reverted that change.

If I run cluster verify I get the same Unknown CA message, so I can't seem to repair my cluster until I get the 2nd node back online, but can't seem to fix that with fixing the CA issue so it's a case of chicken and egg.

I appreciate this is a really old cluster version, and we are looking to deprecate it but for that I need the cluster online.

I'd appreciate any feedback, thanks.

**Comment by saschalucas** [comment]
Hi,

I recently had the same issue with a two node Cluster using Ganeti-2.14. I observed, that cert renew is broken in two node clusters, after certs has expired.

Just a quick try....  I've forced the current known master to always start by inserting `--no-voting --yes-do-it` in `/etc/default/ganeti`. In 2.14 this is `WCONFD_ARGS` and `LUXID_ARGS`. Maybe 2.12 has still the single `MASTERD`??? Bring up the master (`/etc/init.d/ganeti restart`). After that `gnt-cluster renew-crypto` worked. If everything is OK, remove the no-voting from defaults file and restart services on master.

HTH, Sascha.

**Comment by runtman** [comment]
Hey, thanks for the reply. Both nodes do currently think gnt-1 is the master, so I don't have much issue there, and on the master, all services are running. It just seems to be any cluster wide operation leads to a `gnutls_handshake() failed: CA is unknown` or similar.

Stopping instances, trying to set the 2nd master to online from offline, or migrating instances. The cluster is running but essentially useless.

You mentioned the node certificates fails when expired, I did actually renew them all manually using openssl.

**Comment by runtman** [comment]
So I tried that running without certificate part and still got the issue.

`root@phx-gnt-1[A79]:~$ rm /var/lib/ganeti/client.pem
rm: cannot remove ‘/var/lib/ganeti/client.pem’: No such file or directory

root@phx-gnt-1[A79]:~$ rm /var/lib/ganeti/ssconf_master_candidate_certs
rm: cannot remove ‘/var/lib/ganeti/ssconf_master_candidate_certs’: No such file or directory

root@phx-gnt-1[A79]:~$ /etc/init.d/ganeti start
 * Starting Ganeti cluster                                                                             * ganeti-noded...                                                                             [ OK ]
 * ganeti-wconfd...
Error in the RPC HTTP reply from 'Node {nodeName = "phx-gnt-2x.com", nodePrimaryIp = "172.17.103.17", nodeSecondaryIp = "172.17.103.17", nodeMasterCandidate = False, nodeOffline = True, nodeDrained = False, nodeGroup = "bcae0c5a-6e90-4ac9-bfc6-bc5a52411cd7", nodeMasterCapable = True, nodeVmCapable = True, nodeNdparams = PartialNDParams {ndpOobProgramP = Nothing, ndpSpindleCountP = Nothing, ndpExclusiveStorageP = Nothing, ndpOvsP = Nothing, ndpOvsNameP = Nothing, ndpOvsLinkP = Nothing, ndpSshPortP = Nothing, ndpCpuSpeedP = Nothing}, nodePowered = True, nodeCtime = Thu Oct 29 13:12:29 UTC 2015, nodeMtime = Tue Dec 14 10:30:25 UTC 2021, nodeUuid = "199b889b-1441-46f3-a557-7baee8a13951", nodeSerial = 4, nodeTags = fromList []}': CurlLayerError "code: CurlSSLConnectError, explanation: gnutls_handshake() failed: CA is unknown"`

Could this be related to `rapi.pem` `spice-ca.pem` or `spice.pem` do you think? I renewed those via openssl when I noticed the original command had failed.

**Comment by runtman** [comment]
I think this is my issue:  https://ganeti.googlesource.com/wiki/+/refs/heads/master/GanetiAndSSL.md#cn_encodings

specifically: `unning inside a cluster or if the server.pem is very old so that it was created with a different openssl/gnutls version than the new client.pem.`

Issue is, it doesn't describe how to fix it :D

**Comment by runtman** [comment]
There was a typo, the file to delete was `ssconf_master_candidates_certs` not `ssconf_master_candidate_certs`. I may be closer now.

**Comment by runtman** [comment]
Now when I go to readd the 2nd node (which is marked as offline) I get

```
Failure: command execution error:
Node daemon on phx-gnt-2.x didn't answer queries within 10.0 seconds
```

And on the logs of node 2 I see:

```
2021-12-14 22:36:15,395: ganeti-noded pid=12373 ERROR Error while handling request from 172.17.103.16:15768
Traceback (most recent call last):
  File "/usr/local/share/ganeti/2.12/ganeti/http/server.py", line 594, in _IncomingConnection
    self.request_executor(self, self.handler, connection, client_addr)
  File "/usr/local/share/ganeti/2.12/ganeti/server/noded.py", line 158, in __init__
    http.server.HttpServerRequestExecutor.__init__(self, *args, **kwargs)
  File "/usr/local/share/ganeti/2.12/ganeti/http/server.py", line 422, in __init__
    http.Handshake(sock, self.WRITE_TIMEOUT)
  File "/usr/local/share/ganeti/2.12/ganeti/http/__init__.py", line 539, in Handshake
    raise HttpError("Error in SSL handshake: %s" % err)
HttpError: Error in SSL handshake: ([('SSL routines', 'SSL3_GET_CLIENT_CERTIFICATE', 'no certificate returned')],)
```

**Comment by runtman** [comment]
Running these

```
gnt-cluster renew-crypto --new-rapi-certificate
gnt-cluster renew-crypto --new-spice-certificate
```

seems to cause the same issue, node 2 sees this in the logs

```
2021-12-14 22:49:34,094: ganeti-noded pid=13641 ERROR Error while handling request from 172.17.103.16:15901
Traceback (most recent call last):
  File "/usr/local/share/ganeti/2.12/ganeti/http/server.py", line 594, in _IncomingConnection
    self.request_executor(self, self.handler, connection, client_addr)
  File "/usr/local/share/ganeti/2.12/ganeti/server/noded.py", line 158, in __init__
    http.server.HttpServerRequestExecutor.__init__(self, *args, **kwargs)
  File "/usr/local/share/ganeti/2.12/ganeti/http/server.py", line 422, in __init__
    http.Handshake(sock, self.WRITE_TIMEOUT)
  File "/usr/local/share/ganeti/2.12/ganeti/http/__init__.py", line 539, in Handshake
    raise HttpError("Error in SSL handshake: %s" % err)
HttpError: Error in SSL handshake: ([('SSL routines', 'SSL3_GET_CLIENT_CERTIFICATE', 'no certificate returned')],)
```

**Comment by runtman** [comment]
I seem to have the same issue as: https://github.com/jfut/ganeti-rpm/issues/18

**Comment by runtman** [comment]
I really should have read what you wrote more accurately. So I think the fix was a combination of things.

1. Stop ganeti on both nodes `/etc/init.d/ganeti stop`
2. Remove `client.pem` and `ssconf_master_candidates_certs` on both nodes
3. create `/etc/default/ganeti` file on the current master with the following: 
```
WCONFD_ARGS="--no-voting --yes-do-it"
LUXID_ARGS="--no-voting --yes-do-it"
```
4. Start ganeti on secondary
5. Start ganeti on primary.
6. Rerun `gnt-cluster renew-crypto --new-node-certificates`

**Comment by runtman** [comment]
> Hi,
> 
> I recently had the same issue with a two node Cluster using Ganeti-2.14. I observed, that cert renew is broken in two node clusters, after certs has expired.
> 
> Just a quick try.... I've forced the current known master to always start by inserting `--no-voting --yes-do-it` in `/etc/default/ganeti`. In 2.14 this is `WCONFD_ARGS` and `LUXID_ARGS`. Maybe 2.12 has still the single `MASTERD`??? Bring up the master (`/etc/init.d/ganeti restart`). After that `gnt-cluster renew-crypto` worked. If everything is OK, remove the no-voting from defaults file and restart services on master.
> 
> HTH, Sascha.

Thank you <3

**Comment by saschalucas** [comment]
> I really should have read what you wrote more accurately. So I think the fix was a combination of things.

:thumbsup: I'm glade to hear you manged to get it working again. Yes seems a combination ...

> WCONFD_ARGS="--no-voting --yes-do-it"
> LUXID_ARGS="--no-voting --yes-do-it"

Don't forget to remove this ARGS and restart services on master after everything works again.
