### ISSUE TITLE
NIC hotplug with vhost_net=True broken

### ISSUE THREAD

**Issue by saschalucas** [ganeti/ganeti#1651]
While trying to investigate #1649 I discovered an other issue regarding NIC hotplug. When the KVM HV parameter `vhost_net` is set to=`True`, NIC-Hotplug fails with:
```
# Ganeti=https://github.com/ganeti/ganeti:master OS=debian-bullseye 
root@master:~# gnt-instance modify --hotplug --net add:network=vm-net test.vm
Sun Feb  6 11:50:42 2022  - INFO: Trying to hotplug device...
Sun Feb  6 11:50:42 2022  - WARNING: Could not hotplug device: Error while executing backend function: kvm: error executing the netdev_add command: Invalid parameter type for 'vhost', expected: boolean (GenericError):
```
According [this Issue](https://bugzilla.redhat.com/show_bug.cgi?id=1832710#c2), Qemu switched `netdev_add` to a type-safe representation. Ganeti currently sends `"vhost": "on"` as string: https://github.com/ganeti/ganeti/blob/7382df3b1494b1247cd8767d1e740f13f46b729a/lib/hypervisor/hv_kvm/monitor.py#L504-L508
Changing to `"vhost": True` solved the problem.

There might be more issues regarding types in QMP.

@rbott is `vhost_net` enabled in the QA-Suite?

At least no one should use virtio-networking without vhost.

**Comment by rbott** [comment]
Thanks for finding this @saschalucas. `vhost_net` is currently set to its default in the QA suite environment and also not in the list of alternating hvparams (although right now I cannot recall why I did not add it, maybe I simply forgot to do so).
