### ISSUE TITLE
REGRESSION: wrong oper_ram reported by gnt-instance

### ISSUE THREAD

**Issue by zen2** [ganeti/ganeti#1656]
We use on our cluster a script that print status of all instances with instances informations related to cpu, ram, disk_type, disks_sizes, drbd_nodes. For this purpose we use this command:
`gnt-instance list -o name,oper_ram,be/minmem,be/maxmem`
(I removed intentionally not relevant list options for this issue)

On ganeti 2.15: oper_ram report actual memory usage
On ganeti 3.0.1:  oper_ram report the same thing that be/maxmem or be/memory (since it's designed to be the same)

To reproduce this issue:
```
gnt-instance add -B vcpus=1,minmem=1G,maxmem=8G -t plain -s 10G test.instance.vm
gnt-instance start test.instance.vm
gnt-instance list -o name,oper_ram,be/minmem,be/maxmem
# should report: test.instance.vm 8G 1G 8G
gnt-instance modify --force --runtime-memory 4G test.instance.vm
gnt-instance list -o name,oper_ram,be/minmem,be/maxmem
# should report: test.instance.vm 4G 1G 8G
# but not on Ganeti 3.0.1 that will report: test.instance.vm 8G 1G 8G
```

This issue is problematic on our cluster because for our usage we always create instances with a min/max memory and we use a hook to resize the runtime memory at start/stop/reboot/modify according to memory size defined outside ganeti.
That permits us to reduce or grow on the fly memory used by instances without service interruption.
So actually we can't see real memory usage of instances with ganeti 3.0.1.

Related: https://github.com/ganeti/ganeti/issues/1642

**Comment by rbott** [comment]
From a quick glance at the code, there _might_ be an issue here:

https://github.com/ganeti/ganeti/blob/59c55f58b2d2797ebe297650f6f2c3a459ae524a/lib/hypervisor/hv_kvm/__init__.py#L1095-L1104

I will do some tests/debugging in the next days and see if that is correct.

**Comment by rbott** [comment]
Hi @zen2, I have investigated this issue but it seems rather related to the guest. It works fine on both the stable-3.0 branch and also on latest master when the guest has loaded these two modules:

* virtio_pci
* virtio_balloon

When they are not present inside the guest, I get the exact same behavior as you described. Could you double-check your guests if the modules are present (or directly built into the kernel).

I tested this on Debian Bullseye running both Ganeti versions mentioned above. I used direct kernel boot (using the hosts's kernel image) and a custom initrd which contains all virtio modules.

**Comment by rbott** [comment]
I will close this issue for now. If you have new informatino, please feel free to re-open.

**Comment by zen2** [comment]
REOPENING 3 years later:

We have migrated our cluster from Ganeti 2.15 to 3.0.2 and `memory oper_ram` still report the same ram value than `be/maxmem` after have started the instance with `be/maxmem` and reduced it using `gnt-instance --runtime-memory` via hooks.

I have check kernel configuration used by kernel (no modules, inside guest) and both options `virtio_pci` and `virtio_balloon` are enabled (all virtio options are enabled).

So i wonder what can be the difference with our setup ?

Ganeti upgrade have been done along whole system upgrade (gentoo linux) and so qemu have been upgraded to 8.2.7.
qemu installed version doesn't have actually jemalloc support. Could it be related ?
Is Debian use jemalloc for qemu ?
