### ISSUE TITLE
API documentation 

### ISSUE THREAD

**Issue by tristanlatr** [ganeti/ganeti#1664]
Hello, 

I saw that you don't have currently [API documentation](https://docs.ganeti.org/docs/ganeti/3.0/api/py/) in place.
I'de suggest to use, [pydoctor](https://github.com/twisted/pydoctor). It supports Epytext and it's actively used and maintained by the twisted community. If your build was working with `epydoc`, it should not be hard to make to work with `pydoctor` since their CLI interface largely ressembles.

Tell me what you think,

Thanks

**Comment by saschalucas** [comment]
Thanks @tristanlatr for your information. `pydoctor` looks promising: it's part of Debian and seems to work as a drop-in replacement for `epydoc`. I definitely consider using it.

**Comment by tristanlatr** [comment]
> seems to work as a drop-in replacement for epydoc

Well not exactly, there are features that are not present in epydoc, and the opposite is also true. There are a couple of differences is the CLI too, but overall should be quite easy to make it work.

Talk to you later,

**Comment by newellz2** [comment]
I created a pull request (#1676) for my commit to change the py-apidoc build target to use pydoctor. pydoctor seems to work well.
