### ISSUE TITLE
pycodestyle, formerly called pep8, produces many errors

### ISSUE THREAD

**Issue by newellz2** [ganeti/ganeti#1674]
I modified `configure.ac` and `Makefile.am` to use `pycodestyle` version 2.6.0, which is the release available via `apt install pycodestyle` in Debian bullseye. When you run `make pycodestyle` (formerly `make pep8`) now, many new style errors are shown.

Here is my commit with the changes to use `pycodestyle`:
https://github.com/ganeti/ganeti/commit/dfab91925224b5640d4c75de105e8c1b8df0e6bc

I'm fine with issuing pull requests for many of these issues, but I want to know:

1. Do we want to use a newer version of pycodestyle?
2. Are you OK with me issuing pull requests for these style errors?

## `pycodestyle` `--statistics` Output
```
...
2540    E114 indentation is not a multiple of four (comment)
1       E115 expected an indented block (comment)
5       E116 unexpected indentation (comment)
1       E117 over-indented (comment)
58      E126 continuation line over-indented for hanging indent
24      E128 continuation line under-indented for visual indent
130     E129 visually indented line with same indent as next logical line
110     E131 continuation line unaligned for hanging indent
1       E211 whitespace before '('
5       E226 missing whitespace around arithmetic operator
5       E231 missing whitespace after ','
1       E251 unexpected spaces around keyword / parameter equals
39      E265 block comment should start with '# '
15      E266 too many leading '#' for block comment
1       E272 multiple spaces before keyword
6       E302 expected 2 blank lines, found 1
4       E303 too many blank lines (2)
7       E305 expected 2 blank lines after class or function definition, found 1
3       E401 multiple imports on one line
15      E402 module level import not at top of file
2       E502 the backslash is redundant between brackets
19      E713 test for membership should be 'not in'
27      E722 do not use bare 'except'
59      E731 do not assign a lambda expression, use a def
7       E741 ambiguous variable name 'l'
36      W503 line break before binary operator
464     W504 line break after binary operator
1       W605 invalid escape sequence '\.'
```

**Comment by saschalucas** [comment]
Thank you @newellz2 for your contribution. I didn't noticed that `pep8` is now `pycodestyle`. And to be honest ATM we don't have someone caring for code style. So I would highly appreciate your contribution in that area.

Maybe my skills are enough for reviewing code style PRs :smile:?

**Comment by newellz2** [comment]
I'm closing this issue. I starting to send pull requests. :)
