### ISSUE TITLE
move-instance optimisation: don't wait for DRBD sync

### ISSUE THREAD

**Issue by anarcat** [ganeti/ganeti#1702]
when we create VMs in the DRBD backend, we pass `--no-wait-for-sync` to speed up the instance creation. the downside is the VM is sitting there syncing the DRBD disks for a while, but at least it's responsive quickly and anyway we typically have post-creation bootstrapping to do before the machine is actually in production.

when i *move* an instance with the `move-instance` command, however, it doesn't specify that option and spends a *long* time doing that silly transfer.

let's optimize this out or at least make it configurable.

**Comment by jcharaoui** [comment]
There is also a way to simply bypass the initial sync, which is (often) useless for new volumes:

>     # drbdadm create-md <resource>  -  (do this on both nodes)
>     # drbdadm up <resource>  -  (do this on both nodes)
>     # drbdadm -- --clear-bitmap new-current-uuid <resource>  -  (do this on secondary node)
>     # drbdadm primary <resource>  -  (do this on primary node)

This is what one of the core developpers of DRBD recommend.
See https://www.mail-archive.com/drbd-user@lists.linbit.com/msg12212.html

**Comment by anarcat** [comment]
On 2023-03-21 11:23:45, Jerome Charaoui wrote:
> There is also a way to simply bypass the initial sync, which is (often) useless for new volumes:
>
>>     # drbdadm create-md <resource>  -  (do this on both nodes)
>>     # drbdadm up <resource>  -  (do this on both nodes)
>>     # drbdadm -- --clear-bitmap new-current-uuid <resource>  -  (do this on secondary node)
>>     # drbdadm primary <resource>  -  (do this on primary node)
>
> This is what one of the core developpers of DRBD recommend.
> See ***@***.***/msg12212.html

While this is a great idea, this is something that could be done for
instance creation, in general. We already have a tweak that allows us to
create the DRBD pair without waiting for it, I'm suggesting we just
enable that bypass for this operation here.

But yes, that would be a nice optimization to make in create-instance
itself, maybe we even already do this! I haven't checked.

**Comment by zen2** [comment]
> But yes, that would be a nice optimization to make in create-instance itself, maybe we even already do this! I haven't checked.

That could be used too when adding a new disk to an existing instance too.
