### ISSUE TITLE
python-3.12: module imp is removed

### ISSUE THREAD

**Issue by saschalucas** [ganeti/ganeti#1764]
```
PYTHONPATH=. ./autotools/run-in-tempdir /tmp/cc6ec8b83188ed1947faf579b43d3d5486364d13/thielema_colon_makefile.ghc-individual/./autotools/build-rpc lib/rpc_defs.py > lib/_generated_rpc.py
Traceback (most recent call last):
  File "/tmp/cc6ec8b83188ed1947faf579b43d3d5486364d13/thielema_colon_makefile.ghc-individual/./autotools/build-rpc", line 46, in <module>
    from ganeti import build
  File "/tmp/gntbuild.rsPPj8s9/ganeti/build/__init__.py", line 32, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
make: *** [Makefile:4715: lib/_generated_rpc.py] Error 1
make: *** Deleting file 'lib/_generated_rpc.py'
```
maybe  in favor of `importlib`?

**Comment by thielema** [comment]
Does someone know what ganeti/lib/build/__init__.py is useful for, at all?
It looks like a pretty low-level hack to Python's module imports. What is wrong with Python's module system that requires this patch?

**Comment by thielema** [comment]
It seems like `imp` was intended for dynamically loading and reloading modules and managing state of modules.
Is this functionality used in Ganeti, at all? The initial comment of the `ganeti/lib/build/init.py` says:
"Module used during the Ganeti build process"
If this functionality is actually used, it still sounds like bad style.

**Comment by codefritzel** [comment]
Apart from generated_rpc, this is still used in a few other places:
```
root@01c5940a050b:/workspaces/ganeti# grep -nr LoadModule
autotools/build-rpc:200:    module = build.LoadModule(filename)
autotools/build-bash-completion:886:                                         build.LoadModule(filename)))
autotools/check-imports:54:  load_module = build.LoadModule
lib/build/__init__.py:36:def LoadModule(filename):
test/py/docs_unittest.py:325:    return build.LoadModule("scripts/%s" % name)
```

@saschalucas  can you please test #1771 ?

I agree with @thielema here, but we should solve this in the future. The python 3.12 support is more important for now.

**Comment by saschalucas** [comment]
Actually I have not much glue about this "python build code". As @codefritzel already pointed out, it seems that some other parts like RPC defs or bash-completion is generated out of it. Also `check-imports` sound like it is used for "simulating" a run of a python module to identify possible problems beforehand???
