### ISSUE TITLE
make py-tests fails although tests were successful

### ISSUE THREAD

**Issue by codefritzel** [ganeti/ganeti#1780]
This currently only happens in Ubuntu noble:
<details>
cd . && test -h "ganeti" || { rm -f ganeti && ln -s lib ganeti; }
[GHC]: src/Ganeti/Hs2Py/GenOpCodes.o <- cabal_macros.h src/Ganeti/Hs2Py/GenOpCodes.hs src/Ganeti/THH.hi src/Ganeti/THH.o src/Ganeti/OpCodes.hi src/Ganeti/OpCodes.o
compilation IS NOT required
error=; \
for file in doc/examples/rapi_testutils.py test/py/cmdlib/backup_unittest.py test/py/cmdlib/cluster_unittest.py test/py/cmdlib/cmdlib_unittest.py test/py/cmdlib/group_unittest.py test/py/cmdlib/instance_unittest.py test/py/cmdlib/instance_migration_unittest.py test/py/cmdlib/instance_query_unittest.py test/py/cmdlib/instance_storage_unittest.py test/py/cmdlib/node_unittest.py test/py/cmdlib/test_unittest.py test/py/cfgupgrade_unittest.py test/py/docs_unittest.py test/py/ganeti.asyncnotifier_unittest.py test/py/ganeti.backend_unittest-runasroot.py test/py/ganeti.backend_unittest.py test/py/ganeti.bootstrap_unittest.py test/py/ganeti.cli_unittest.py test/py/ganeti.cli_opts_unittest.py test/py/ganeti.client.gnt_cluster_unittest.py test/py/ganeti.client.gnt_instance_unittest.py test/py/ganeti.client.gnt_job_unittest.py test/py/ganeti.compat_unittest.py test/py/ganeti.confd.client_unittest.py test/py/ganeti.config_unittest.py test/py/ganeti.constants_unittest.py test/py/ganeti.daemon_unittest.py test/py/ganeti.errors_unittest.py test/py/ganeti.hooks_unittest.py test/py/ganeti.ht_unittest.py test/py/ganeti.http_unittest.py test/py/ganeti.hypervisor.hv_chroot_unittest.py test/py/ganeti.hypervisor.hv_fake_unittest.py test/py/ganeti.hypervisor.hv_kvm_unittest.py test/py/ganeti.hypervisor.hv_lxc_unittest.py test/py/ganeti.hypervisor.hv_xen_unittest.py test/py/ganeti.hypervisor_unittest.py test/py/ganeti.impexpd_unittest.py test/py/ganeti.jqueue_unittest.py test/py/ganeti.jstore_unittest.py test/py/ganeti.locking_unittest.py test/py/ganeti.luxi_unittest.py test/py/ganeti.masterd.iallocator_unittest.py test/py/ganeti.masterd.instance_unittest.py test/py/ganeti.mcpu_unittest.py test/py/ganeti.netutils_unittest.py test/py/ganeti.objects_unittest.py test/py/ganeti.opcodes_unittest.py test/py/ganeti.outils_unittest.py test/py/ganeti.ovf_unittest.py test/py/ganeti.qlang_unittest.py test/py/ganeti.query_unittest.py test/py/ganeti.rapi.baserlib_unittest.py test/py/ganeti.rapi.client_unittest.py test/py/ganeti.rapi.resources_unittest.py test/py/ganeti.rapi.rlib2_unittest.py test/py/ganeti.rapi.testutils_unittest.py test/py/ganeti.rpc_unittest.py test/py/ganeti.rpc.client_unittest.py test/py/ganeti.runtime_unittest.py test/py/ganeti.serializer_unittest.py test/py/ganeti.server.rapi_unittest.py test/py/ganeti.ssconf_unittest.py test/py/ganeti.ssh_unittest.py test/py/ganeti.storage.bdev_unittest.py test/py/ganeti.storage.container_unittest.py test/py/ganeti.storage.drbd_unittest.py test/py/ganeti.storage.filestorage_unittest.py test/py/ganeti.storage.gluster_unittest.py test/py/ganeti.tools.burnin_unittest.py test/py/ganeti.tools.ensure_dirs_unittest.py test/py/ganeti.tools.node_daemon_setup_unittest.py test/py/ganeti.tools.prepare_node_join_unittest.py test/py/ganeti.uidpool_unittest.py test/py/ganeti.utils.algo_unittest.py test/py/ganeti.utils.filelock_unittest.py test/py/ganeti.utils.hash_unittest.py test/py/ganeti.utils.io_unittest-runasroot.py test/py/ganeti.utils.io_unittest.py test/py/ganeti.utils.log_unittest.py test/py/ganeti.utils.livelock_unittest.py test/py/ganeti.utils.lvm_unittest.py test/py/ganeti.utils.mlock_unittest.py test/py/ganeti.utils.nodesetup_unittest.py test/py/ganeti.utils.process_unittest.py test/py/ganeti.utils.retry_unittest.py test/py/ganeti.utils.security_unittest.py test/py/ganeti.utils.storage_unittest.py test/py/ganeti.utils.text_unittest.py test/py/ganeti.utils.version_unittest.py test/py/ganeti.utils.wrapper_unittest.py test/py/ganeti.utils.x509_unittest.py test/py/ganeti.utils.bitarrays_unittest.py test/py/ganeti.utils_unittest.py test/py/ganeti.vcluster_unittest.py test/py/ganeti.workerpool_unittest.py test/py/pycurl_reset_unittest.py test/py/qa.qa_config_unittest.py test/py/tempfile_fork_unittest.py; \
  do if ! PYTHONPATH=.:./test/py TOP_SRCDIR=/work TOP_BUILDDIR=/work PYTHON=/usr/bin/python3 FAKEROOT= ./autotools/run-in-tempdir /work/autotools/testrunner $file; then error=1; fi; \
done; \
test -z "$error"
Testing features ...
Testing node evacuation ...
Testing listing instances ...
Testing renaming instance ...
Testing renaming instance with error ...
Success!
Running backup_unittest.py
...................
----------------------------------------------------------------------
Ran 19 tests in 0.055s

OK
/tmp/gntbuild.sijN9S9o/test/py/cmdlib/cluster_unittest.py:219: SyntaxWarning: invalid escape sequence '\('
  self.ExecOpCodeExpectOpPrereqError(op, "still 2 node\(s\)")
/tmp/gntbuild.sijN9S9o/test/py/cmdlib/cluster_unittest.py:227: SyntaxWarning: invalid escape sequence '\('
  self.ExecOpCodeExpectOpPrereqError(op, "still 2 instance\(s\)")
/tmp/gntbuild.sijN9S9o/test/py/cmdlib/cluster_unittest.py:1137: SyntaxWarning: invalid escape sequence '\('
  "following nodes \(and their instances\) belong to a non existing group")
/tmp/gntbuild.sijN9S9o/test/py/cmdlib/cluster_unittest.py:1798: SyntaxWarning: invalid escape sequence '\('
  self.mcpu.assertLogContainsRegex("instance has offline secondary node\(s\)")
Running cluster_unittest.py
........................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 216 tests in 0.570s

OK
Running cmdlib_unittest.py
.........................................................
----------------------------------------------------------------------
Ran 57 tests in 0.004s

OK
Running group_unittest.py
..........................
----------------------------------------------------------------------
Ran 26 tests in 0.040s

OK
/tmp/gntbuild.SLsgpESg/test/py/cmdlib/instance_unittest.py:2699: SyntaxWarning: invalid escape sequence '\['
  msg = "Disk nodes are \['mock_node_1134'\]"
/tmp/gntbuild.SLsgpESg/test/py/cmdlib/instance_unittest.py:3240: SyntaxWarning: invalid escape sequence '\('
  op, "Can't use group\(s\) .* as targets, they are used by the"
Running instance_unittest.py
.......................................................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 359 tests in 1.577s

OK
Running instance_migration_unittest.py
......
----------------------------------------------------------------------
Ran 6 tests in 0.018s

OK
Running instance_query_unittest.py

----------------------------------------------------------------------
Ran 0 tests in 0.000s

NO TESTS RAN
Running instance_storage_unittest.py
............
----------------------------------------------------------------------
Ran 12 tests in 0.022s

OK
Running node_unittest.py
.......................
----------------------------------------------------------------------
Ran 23 tests in 0.076s

OK
Running test_unittest.py
..................
----------------------------------------------------------------------
Ran 18 tests in 0.028s

OK
Running cfgupgrade_unittest.py
.................................................
----------------------------------------------------------------------
Ran 49 tests in 9.540s

OK
/tmp/gntbuild.fMxdZSLD/test/py/docs_unittest.py:119: SyntaxWarning: invalid escape sequence '\s'
  hooks_paths = frozenset(re.findall("^:directory:\s*(.+)\s*$", hooksdoc,
Running docs_unittest.py
...
----------------------------------------------------------------------
Ran 3 tests in 0.085s

OK
Running ganeti.asyncnotifier_unittest.py
.../usr/lib/python3/dist-packages/asyncore/asyncore.py:595: ResourceWarning: unclosed file <asyncore.asyncore.file_wrapper object at 0x7f698aae5bb0>
  warnings.warn("unclosed file %r" % self, ResourceWarning,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3/dist-packages/asyncore/asyncore.py:595: ResourceWarning: unclosed file <asyncore.asyncore.file_wrapper object at 0x7f698aae6930>
  warnings.warn("unclosed file %r" % self, ResourceWarning,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3/dist-packages/asyncore/asyncore.py:595: ResourceWarning: unclosed file <asyncore.asyncore.file_wrapper object at 0x7f698aae6a20>
  warnings.warn("unclosed file %r" % self, ResourceWarning,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3/dist-packages/asyncore/asyncore.py:595: ResourceWarning: unclosed file <asyncore.asyncore.file_wrapper object at 0x7f698aae7110>
  warnings.warn("unclosed file %r" % self, ResourceWarning,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3/dist-packages/asyncore/asyncore.py:595: ResourceWarning: unclosed file <asyncore.asyncore.file_wrapper object at 0x7f698aae7230>
  warnings.warn("unclosed file %r" % self, ResourceWarning,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3/dist-packages/asyncore/asyncore.py:595: ResourceWarning: unclosed file <asyncore.asyncore.file_wrapper object at 0x7f698aae7320>
  warnings.warn("unclosed file %r" % self, ResourceWarning,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3/dist-packages/asyncore/asyncore.py:595: ResourceWarning: unclosed file <asyncore.asyncore.file_wrapper object at 0x7f698aae7800>
  warnings.warn("unclosed file %r" % self, ResourceWarning,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3/dist-packages/asyncore/asyncore.py:595: ResourceWarning: unclosed file <asyncore.asyncore.file_wrapper object at 0x7f698aae7920>
  warnings.warn("unclosed file %r" % self, ResourceWarning,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3/dist-packages/asyncore/asyncore.py:595: ResourceWarning: unclosed file <asyncore.asyncore.file_wrapper object at 0x7f698aae7a10>
  warnings.warn("unclosed file %r" % self, ResourceWarning,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
....
----------------------------------------------------------------------
Ran 7 tests in 0.026s

OK
WARNING: FAKEROOT variable not set, skipping test/py/ganeti.backend_unittest-runasroot.py
Running ganeti.backend_unittest.py
.................................................................................................
----------------------------------------------------------------------
Ran 97 tests in 0.566s

OK
Running ganeti.bootstrap_unittest.py
..............
----------------------------------------------------------------------
Ran 14 tests in 0.001s

OK
Running ganeti.cli_unittest.py
.........................................................................
----------------------------------------------------------------------
Ran 73 tests in 0.008s

OK
Running ganeti.cli_opts_unittest.py
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
Running ganeti.client.gnt_cluster_unittest.py
.....................
----------------------------------------------------------------------
Ran 21 tests in 0.029s

OK
Running ganeti.client.gnt_instance_unittest.py
..........
----------------------------------------------------------------------
Ran 10 tests in 0.001s

OK
Running ganeti.client.gnt_job_unittest.py
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
Running ganeti.compat_unittest.py
.........
----------------------------------------------------------------------
Ran 9 tests in 0.000s

OK
Running ganeti.confd.client_unittest.py
............
----------------------------------------------------------------------
Ran 12 tests in 0.002s

OK
Running ganeti.config_unittest.py
............................
----------------------------------------------------------------------
Ran 28 tests in 0.133s

OK
Running ganeti.constants_unittest.py
.................
----------------------------------------------------------------------
Ran 17 tests in 0.001s

OK
Running ganeti.daemon_unittest.py
...........ssssss
----------------------------------------------------------------------
Ran 17 tests in 0.001s

OK (skipped=6)
Running ganeti.errors_unittest.py
....
----------------------------------------------------------------------
Ran 4 tests in 0.000s

OK
Running ganeti.hooks_unittest.py
...............
----------------------------------------------------------------------
Ran 15 tests in 0.011s

OK
Running ganeti.ht_unittest.py
...........................
----------------------------------------------------------------------
Ran 27 tests in 0.001s

OK
Running ganeti.http_unittest.py
.................................
----------------------------------------------------------------------
Ran 33 tests in 0.160s

OK
Running ganeti.hypervisor.hv_chroot_unittest.py
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
Running ganeti.hypervisor.hv_fake_unittest.py
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
Running ganeti.hypervisor.hv_kvm_unittest.py
...........................................................
----------------------------------------------------------------------
Ran 59 tests in 0.035s

OK
Running ganeti.hypervisor.hv_lxc_unittest.py
....................
----------------------------------------------------------------------
Ran 20 tests in 0.003s

OK
Running ganeti.hypervisor.hv_xen_unittest.py
.........................................................................
----------------------------------------------------------------------
Ran 73 tests in 0.957s

OK
Running ganeti.hypervisor_unittest.py
...
----------------------------------------------------------------------
Ran 3 tests in 0.000s

OK
Running ganeti.impexpd_unittest.py
...s....
----------------------------------------------------------------------
Ran 8 tests in 0.041s

OK (skipped=1)
Running ganeti.jqueue_unittest.py
..........................................
----------------------------------------------------------------------
Ran 42 tests in 0.047s

OK
Running ganeti.jstore_unittest.py
.........
----------------------------------------------------------------------
Ran 9 tests in 0.006s

OK
Running ganeti.locking_unittest.py
..............................................
----------------------------------------------------------------------
Ran 46 tests in 1.501s

OK
Running ganeti.masterd.iallocator_unittest.py
.........
----------------------------------------------------------------------
Ran 9 tests in 0.000s

OK
Running ganeti.masterd.instance_unittest.py
...........
----------------------------------------------------------------------
Ran 11 tests in 0.001s

OK
Running ganeti.mcpu_unittest.py
...........
----------------------------------------------------------------------
Ran 11 tests in 0.002s

OK
Running ganeti.netutils_unittest.py
............................sss.............
----------------------------------------------------------------------
Ran 44 tests in 0.003s

OK (skipped=3)
Running ganeti.objects_unittest.py
........................................
----------------------------------------------------------------------
Ran 40 tests in 0.004s

OK
Running ganeti.opcodes_unittest.py
...............
----------------------------------------------------------------------
Ran 15 tests in 0.011s

OK
Running ganeti.outils_unittest.py
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
/tmp/gntbuild.eXaYoHif/test/py/ganeti.ovf_unittest.py:552: SyntaxWarning: invalid escape sequence '\S'
  (self.importer.input_dir, path), "file format: (\S+)")
Running ganeti.ovf_unittest.py
................../usr/lib/python3.12/tarfile.py:2221: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  warnings.warn(
...................................................
----------------------------------------------------------------------
Ran 69 tests in 0.042s

OK
Running ganeti.qlang_unittest.py
..........
----------------------------------------------------------------------
Ran 10 tests in 1.307s

OK
Running ganeti.query_unittest.py
..............................
----------------------------------------------------------------------
Ran 30 tests in 0.018s

OK
Running ganeti.rapi.baserlib_unittest.py
.............
----------------------------------------------------------------------
Ran 13 tests in 0.001s

OK
Running ganeti.rapi.client_unittest.py
........................................................................................................................
----------------------------------------------------------------------
Ran 120 tests in 0.021s

OK
Running ganeti.rapi.resources_unittest.py
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
Running ganeti.rapi.rlib2_unittest.py
................................................................................
----------------------------------------------------------------------
Ran 80 tests in 0.571s

OK
Running ganeti.rapi.testutils_unittest.py
.......................
----------------------------------------------------------------------
Ran 23 tests in 0.005s

OK
Running ganeti.rpc_unittest.py
.................................
----------------------------------------------------------------------
Ran 33 tests in 0.007s

OK
Running ganeti.rpc.client_unittest.py
...............
----------------------------------------------------------------------
Ran 15 tests in 0.001s

OK
Running ganeti.runtime_unittest.py
...........
----------------------------------------------------------------------
Ran 11 tests in 0.001s

OK
Running ganeti.serializer_unittest.py
.................
----------------------------------------------------------------------
Ran 17 tests in 0.004s

OK
Running ganeti.server.rapi_unittest.py
..............
----------------------------------------------------------------------
Ran 14 tests in 0.027s

OK
Running ganeti.ssconf_unittest.py
..........................
----------------------------------------------------------------------
Ran 26 tests in 0.038s

OK
Running ganeti.ssh_unittest.py
.......................
----------------------------------------------------------------------
Ran 23 tests in 0.308s

OK
Running ganeti.storage.bdev_unittest.py
.................................
----------------------------------------------------------------------
Ran 33 tests in 0.024s

OK
Running ganeti.storage.container_unittest.py
..
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK
Running ganeti.storage.drbd_unittest.py
....................................
----------------------------------------------------------------------
Ran 36 tests in 0.068s

OK
Running ganeti.storage.filestorage_unittest.py
....s..........s...........
----------------------------------------------------------------------
Ran 27 tests in 0.010s

OK (skipped=2)
Running ganeti.storage.gluster_unittest.py
.......
----------------------------------------------------------------------
Ran 7 tests in 0.010s

OK
Running ganeti.tools.burnin_unittest.py
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
Running ganeti.tools.ensure_dirs_unittest.py
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
Running ganeti.tools.node_daemon_setup_unittest.py
...
----------------------------------------------------------------------
Ran 3 tests in 0.000s

OK
Running ganeti.tools.prepare_node_join_unittest.py
............
----------------------------------------------------------------------
Ran 12 tests in 0.096s

OK
Running ganeti.uidpool_unittest.py
....
----------------------------------------------------------------------
Ran 4 tests in 0.004s

OK
Running ganeti.utils.algo_unittest.py
.......................
----------------------------------------------------------------------
Ran 23 tests in 0.010s

OK
Running ganeti.utils.filelock_unittest.py
..........................
----------------------------------------------------------------------
Ran 26 tests in 1.340s

OK
Running ganeti.utils.hash_unittest.py
.......
----------------------------------------------------------------------
Ran 7 tests in 0.007s

OK
WARNING: FAKEROOT variable not set, skipping test/py/ganeti.utils.io_unittest-runasroot.py
Running ganeti.utils.io_unittest.py
.........................................................................................
----------------------------------------------------------------------
Ran 89 tests in 0.167s

OK
Running ganeti.utils.log_unittest.py
.../usr/lib/python3.12/unittest/case.py:589: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/tmps7i86wvb/reopen.log' mode='a' encoding='utf-8'>
  if method() is not None:
ResourceWarning: Enable tracemalloc to get the object allocation traceback
./usr/lib/python3.12/unittest/case.py:589: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/tmpkiqd60xu/basic.log' mode='a' encoding='utf-8'>
  if method() is not None:
ResourceWarning: Enable tracemalloc to get the object allocation traceback
...
----------------------------------------------------------------------
Ran 7 tests in 0.002s

OK
Running ganeti.utils.livelock_unittest.py
..
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK
Running ganeti.utils.lvm_unittest.py
....
----------------------------------------------------------------------
Ran 4 tests in 0.000s

OK
Running ganeti.utils.mlock_unittest.py
..
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK
Running ganeti.utils.nodesetup_unittest.py
........
----------------------------------------------------------------------
Ran 8 tests in 0.013s

OK
Running ganeti.utils.process_unittest.py
..............................................................
----------------------------------------------------------------------
Ran 62 tests in 9.632s

OK
Running ganeti.utils.retry_unittest.py
..........
----------------------------------------------------------------------
Ran 10 tests in 0.021s

OK
Running ganeti.utils.security_unittest.py
/usr/lib/python3/dist-packages/OpenSSL/crypto.py:1443: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return not_after < datetime.datetime.utcnow()
...
----------------------------------------------------------------------
Ran 3 tests in 0.002s

OK
Running ganeti.utils.storage_unittest.py
............
----------------------------------------------------------------------
Ran 12 tests in 0.001s

OK
Running ganeti.utils.text_unittest.py
.....................................................
----------------------------------------------------------------------
Ran 53 tests in 0.013s

OK
Running ganeti.utils.version_unittest.py
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
Running ganeti.utils.wrapper_unittest.py
..........
----------------------------------------------------------------------
Ran 10 tests in 0.008s

OK
Running ganeti.utils.x509_unittest.py
/usr/lib/python3/dist-packages/OpenSSL/crypto.py:1443: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return not_after < datetime.datetime.utcnow()
...............
----------------------------------------------------------------------
Ran 15 tests in 1.228s

OK
Running ganeti.utils.bitarrays_unittest.py
....
----------------------------------------------------------------------
Ran 4 tests in 0.000s

OK
Running ganeti.utils_unittest.py
...................................................
----------------------------------------------------------------------
Ran 51 tests in 0.009s

OK
Running ganeti.vcluster_unittest.py
.............................
----------------------------------------------------------------------
Ran 29 tests in 0.001s

OK
Running ganeti.workerpool_unittest.py
..........
----------------------------------------------------------------------
Ran 10 tests in 0.311s

OK
  File "/tmp/gntbuild.mICcAYHe/test/py/pycurl_reset_unittest.py", line 91
    #testutils.GanetiTestProgram()
IndentationError: expected an indented block after 'if' statement on line 90
Running qa.qa_config_unittest.py
........................
----------------------------------------------------------------------
Ran 24 tests in 0.214s

OK
Running tempfile_fork_unittest.py
..
----------------------------------------------------------------------
Ran 2 tests in 0.003s

OK
make: *** [Makefile:4922: py-tests] Error 1

</details>

If a test fails, "FAILED" is displayed for the test. But this is not to be found in the output.

**Comment by saschalucas** [comment]
it is this test:
```
root@build:/tmp/running# PYTHONPATH=.:./test/py TOP_SRCDIR=/tmp/running TOP_BUILDDIR=/tmp/running PYTHON=/usr/bin/python3 FAKEROOT=/usr/bin/fakeroot ./autotools/run-in-tempdir /tmp/running/autotools/testrunner test/py/cmdlib/instance_query_unittest.py
Running instance_query_unittest.py

----------------------------------------------------------------------
Ran 0 tests in 0.000s

NO TESTS RAN

root@build:/tmp/running# echo $?
5
```
