### ISSUE TITLE
pycurl_reset_unittest runs for a very long time in noble

### ISSUE THREAD

**Issue by codefritzel** [ganeti/ganeti#1781]
The test "pycurl_reset_unittest" runs for a very long time in Ubuntu noble. The cause is a very large number of a counting loop (for).

The loop counts to `sys.getrefcount(None) * 2`. 
`sys.getrefcount(None)` returns the number of `None` references, the number returned can be very large depending on the python environment (e.g. Ubuntu Noble in Docker):
```
root@309238e94359:/work# python3 -c 'import sys; print(sys.getrefcount(None))'
4294967295
```
outside docker on Ubuntu Jammy:
```
test@test~$ python3 -c 'import sys; print(sys.getrefcount(None))'
4358
```

In the error case, if the refcounter becomes smaller, the test is cancelled with an error, otherwise it runs for a while.
This could be solved by using a high but not too high value for the loop, such as
`for i in range(5000):`

However, I would remove the test for the following reasons:
1. external code outside the project is tested
2. depending on the environment, this test can run for a very long time
3. the function to be tested is not used in Ganeti (see 4fd2660d2d279b67699001a9f5fd9ec945d61e88) 
4. badly designed test and no unittest

If testing is still relevant for this error, then this should be done directly on the productive systems and not at development or compile time.

**Comment by saschalucas** [comment]
> However, I would remove the test for the following reasons:
...
>     3. the function to be tested is not used in Ganeti (see [4fd2660](https://github.com/ganeti/ganeti/commit/4fd2660d2d279b67699001a9f5fd9ec945d61e88))

Agreed. If this is not used, let's remove the test. Besides the issue tested is very old ...
