### ISSUE TITLE
Feature Request: xen_platform_pci option in HVM

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#255]
Originally reported of Google Code with ID 199.

```
What software version are you running? Please provide the output of "gnt-
cluster --version" and "gnt-cluster version".

gnt-cluster (ganeti v2.4.2) 2.4.2

What distribution are you using? Debian Squeeze, amd64


<b>What steps will reproduce the problem?</b>
1. Try to boot VMWare Image who can't deal with /dev/xvdX Devices
<b>2.</b>

<b>Please provide any additional information below.</b>

Please provide the option xen_platform_pci in xen-hvm to disable the XEN PCI Bus. Choosing ioemu / paravirtual as Disk_type makes no difference for the VM. 


```
Originally added on 2011-09-30 09:05:02 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
For Clonezilla or other, becouse the Clonezilla isn't support xvda disk.
```
Originally added on 2012-03-29 16:17:11 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2012-07-19 14:45:15 +0000 UTC.

Added Labels: Type-Enhancement Hypervisor-XenHVM
Changed State: Accepted

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-05-08 08:31:53 +0000 UTC.

Added Labels: SmallTask
Added to Milestone: Release2.9

**Comment by Ganeti-Issues-Migrator** [comment]
```
Move non-critical bugs scheduled for 2.8 or 2.9 to 2.11, as in those versions only critical bug fixes will be integrated.
```
Originally added on 2013-10-30 09:48:16 +0000 UTC.

Added to Milestone: Release2.11
Removed from Milestone: Release2.9

**Comment by ge-fa** [comment]
hypervisor: xen

**Comment by rbott** [comment]
I will go forward here and close this issue. There has not been much traction on the xen hypervisor implementations lately and we can always reopen this if people are actually using xen and missing this feature.
