### ISSUE TITLE
ganeti-rapi should be optional

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#275]
Originally reported of Google Code with ID 219.

```
Just thought about this: on a small cluster or a special deployment, we might not want to control ganeti from outside. As such, it should be possible to disable rapi at configure time *or* runtime, like we do for confd.

Ideally this and confd should be changeable at runtime, not only at configure time, as that prevents distributions from offering both.
```
Originally added on 2012-03-01 16:20:46 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2012-07-19 14:55:23 +0000 UTC.

Added Labels: Type-Enhancement

**Comment by Ganeti-Issues-Migrator** [comment]
```
This is already possible, I believe, by modifying the defaults file. I think it just needs documentation. (no point in adding an extra parameter, if we can do without, right?)

```
Originally added on 2013-02-13 14:46:59 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
No, it's not just that. The code assumes that a healthy cluster means RAPI is running on the master. Hence watcher will restart RAPI if dead, etc.
```
Originally added on 2013-02-13 14:53:22 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Which is not a big deal, if it restarts /bin/true, right? :)
But of course, an extra way to make it not do it is nicer.

Thanks,

Guido

```
Originally added on 2013-02-14 10:20:41 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-04-10 18:11:19 +0000 UTC.

Changed State: Accepted
Added to Milestone: Release2.9

**Comment by Ganeti-Issues-Migrator** [comment]
```
Move non-critical bugs scheduled for 2.8 or 2.9 to 2.11, as in those versions only critical bug fixes will be integrated.
```
Originally added on 2013-10-30 09:48:16 +0000 UTC.

Added to Milestone: Release2.11
Removed from Milestone: Release2.9

**Comment by ge-fa** [comment]
It's possible to bind RAPI to localhost, which is sufficient for now, I guess. IMHO, therefore, this one can be closed.

New state: should be closed

**Comment by iustin** [comment]
Good point, thanks for helping cleanup!

**Comment by ge-fa** [comment]
@iustin Wow, thanks. We're doing a short sprint here on the GanetiCon and will go trough a couple of reports. So in case you have any spare time, expect more updates like the one above coming in during the day.

**Comment by iustin** [comment]
Ah, I see - enjoy the GanetiCon! Will do a bulk run through the updated bugs tonight then.
