### ISSUE TITLE
'gnt-instance batch-create' should be able to create disks in different volume groups

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#277]
Originally reported of Google Code with ID 221.

```
'batch-create' sub-command of 'gnt-instance' command should be able to create disks in different volume groups (as is already supported in 'add' sub-command).

I don't have access to a non-production ganeti setup to help with a full implementation and testing but something along the lines on the attached file might be helpful for any developer who may want to implement it.

```
Originally added on 2012-03-15 11:54:55 +0000 UTC.

Attachments: 
[batch-create-example.py](https://storage.googleapis.com/google-code-attachments/ganeti/issue-221/comment-0/batch-create-example.py)

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2012-07-19 14:55:52 +0000 UTC.

Added Labels: Type-Enhancement

**Comment by apoikos** [comment]
`batch-create` was changed in b0a8e8c2fd (part of 2.7.0) to use `OpInstanceCreate` directly. This means that the instance definition JSON file should support everything `gnt-instance create` supports in a serialized way. Therefore, this issue can be closed.
