### ISSUE TITLE
add support for xen virtual frambuffer (vfb)

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#290]
Originally reported of Google Code with ID 234.

```
What software version are you running? Please provide the output of "gnt-
cluster --version" and "gnt-cluster version".

<b>What distribution are you using?</b>
gentoo amd64

<b>What steps will reproduce the problem?</b>
1. add an xen pvm instance

<b>What is the expected output? What do you see instead?</b>

it should be possible to add vfb option to xen pvm instances

see http://zhigang.org/files/docbook/xen-faq.html#id457301

attached is a small patch to add vfb support for pvm instances


<b>Please provide any additional information below.</b>

```
Originally added on 2012-04-24 14:26:25 +0000 UTC.

Attachments: 
[ganeti-2.5.0-xen-pvm-vfb.patch](https://storage.googleapis.com/google-code-attachments/ganeti/issue-234/comment-0/ganeti-2.5.0-xen-pvm-vfb.patch)

**Comment by Ganeti-Issues-Migrator** [comment]
```
Same, please sign the CLA first and then we can integrate the patch.
```
Originally added on 2012-07-19 15:28:28 +0000 UTC.

Added Labels: Type-Enhancement Hypervisor-XenPVM
Changed State: Accepted

**Comment by Ganeti-Issues-Migrator** [comment]
```
i've signed the cla already.

see this conversation:

http://markmail.org/message/ujl4jagbzajog57c#query:+page:1+mid:rhl5eepl72ccs4rr+state:message

or do i miss something?
```
Originally added on 2012-09-04 15:00:35 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-05-07 14:38:22 +0000 UTC.

Added to Milestone: Release2.8

**Comment by Ganeti-Issues-Migrator** [comment]
```
Move non-critical bugs scheduled for 2.8 or 2.9 to 2.11, as in those versions only critical bug fixes will be integrated.
```
Originally added on 2013-10-30 09:48:16 +0000 UTC.

Added to Milestone: Release2.11
Removed from Milestone: Release2.8

**Comment by ge-fa** [comment]
hypervisor: xen

**Comment by rbott** [comment]
I will go forward here and close this issue. There has not been much traction on the xen hypervisor implementations lately and we can always reopen this if people are actually using xen and missing this feature.
