### ISSUE TITLE
Confusing error messages for instance creation when DNS is misconfigured

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#342]
Originally reported of Google Code with ID 286.

```
Not entirely sure, but it seems that if in DNS, a given hostname points to IP x.x.x.x, but that reverse points to a different name, Ganeti can report very confusing error messages:

$ gnt-instance add .... foo
Error: The given name (bar) does not resolve

We should be able to detect this and explain better the different names.
```
Originally added on 2012-10-30 18:50:44 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-05-09 05:56:50 +0000 UTC.

**Comment by iustin** [comment]
My understanding is that the request is different - perform name check, but do proper reporting, instead of misleading "name does not resolve". However, this is from 2012, let's just close it.
