### ISSUE TITLE
Implementing usb pass-through support for Xen host

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#400]
Originally reported of Google Code with ID 344.

```
Hi,

Would it be possible to have usb pass-through support for Xen host please like it's being implemented for KVM host in issue 340  ?    
Even if it's only usb 1.1 for now (http://wiki.xen.org/wiki/Xen_USB_Passthrough), it'll hopefully allow us to use gsm modem or usb flash drive inside Xen domU 

Thanks. 
```
Originally added on 2013-01-13 11:01:59 +0000 UTC.

Mentioned Issue with GoogleCode ID 340 has been migrated to GitHub with ID #396.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-05-08 08:16:51 +0000 UTC.

Changed State: Accepted

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-05-08 08:18:45 +0000 UTC.

Added Labels: SmallTask

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-07-26 12:46:30 +0000 UTC.

Added to Milestone: Release2.9

**Comment by Ganeti-Issues-Migrator** [comment]
```
Move non-critical bugs scheduled for 2.8 or 2.9 to 2.11, as in those versions only critical bug fixes will be integrated.
```
Originally added on 2013-10-30 09:48:16 +0000 UTC.

Added to Milestone: Release2.11
Removed from Milestone: Release2.9

**Comment by Ganeti-Issues-Migrator** [comment]
```
Removed the milestone as it's long past. As an effort to migrate all our issues to Github, I'll mark this as "Type-Enhancement" and let someone from the community pick it up if they are interested. We'd be happy to accept patches about this.

See https://groups.google.com/forum/#!topic/ganeti/b2-eukpsXpk for more details.

```
Originally added on 2016-12-12 14:56:50 +0000 UTC.

Added Labels: Type-Enhancement
Removed Labels: SmallTask
Changed State: PatchesWelcome
Removed from Milestone: Release2.11

**Comment by ge-fa** [comment]
hypervisor: xen

**Comment by rbott** [comment]
I will go forward here and close this issue. There has not been much traction on the xen hypervisor implementations lately and we can always reopen this if people are actually using xen and missing this feature.
