### ISSUE TITLE
qa: add test with opportunistic_locking on.

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#405]
Originally reported of Google Code with ID 349.

```
qa should test opportunistic_locking in conjunction with at least hail.


```
Originally added on 2013-01-18 14:57:12 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-12-09 14:38:12 +0000 UTC.

Added Labels: Type-Enhancement

**Comment by iustin** [comment]
Closing very old issues.
