### ISSUE TITLE
QA should test hypervisor parameters depending on enabled hypervisors

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#446]
Originally reported of Google Code with ID 390.

```
“qa_instance.TestInstanceModify” has a hardcoded list of hypervisor parameters. Not all hypervisors support the same parameters, so this list should be more flexible and look at the enabled hypervisors.
```
Originally added on 2013-02-27 13:24:52 +0000 UTC.

**Comment by apoikos** [comment]
Enabled hypervisors can be obtained easily through ssconf's `GetHypervisorList()`.

**Comment by rbott** [comment]
That problem is actually solved, `TestInstanceModify()` separates parameters by Hypervisor (currently KVM, XEN-PVM, XEN-HVM and LXC). Therefore closing this.
