### ISSUE TITLE
Old issue tracker 404es

### ISSUE THREAD

**Issue by yiannist** [ganeti/ganeti#48]
It seems that https://code.google.com/p/ganeti/issues is down while the issues haven't migrated yet to Github. The old issue tracker has content of vital importance for us (GRNET) and we think that maybe we should consider reviving it at least until the migration is completed. I think that more people asked for it in IRC, too. So, what's the plan? :)

**Comment by RafaelMarinheiro** [comment]
I've contacted the Google Code team and we already have a backup of those issues. They all should be available in GitHub within the next day or so.

**Comment by RafaelMarinheiro** [comment]
FYI: For now it should be possible to access those issues using the Google Code Archive api:

https://storage.googleapis.com/google-code-archive/v2/code.google.com/ganeti/issues/issue-1.json

**Comment by flokli** [comment]
@RafaelMarinheiro will the issues still get imported into this issue tracker?

**Comment by RafaelMarinheiro** [comment]
All the issues are going to be migrated later today. It will take a couple hours to do so because of the quota restrictions applied by the GitHub API.

After the migration I will also upload a JSON file that maps old issue IDs to the new ones. It will be there just for reference as all the at the issues that mentioned other issues, either in the form of "Issue 1234" or "code.github/....../issue/1234", will also reference the migrated GitHub issues.

**Comment by RafaelMarinheiro** [comment]
This is going slow because we're hitting the API Abuse Rate Limits (which apparently only applies to public repos). All the data is being checkpointed, so there is no major issue there. If needed I will continue this tomorrow

**Comment by RafaelMarinheiro** [comment]
I've added a delay of 10s between each API call. If we don't run into any troubles the migration should end in 13h.

**Comment by RafaelMarinheiro** [comment]
All of the issues should now be available in the GitHub issue tracker. For now we don't expose authorship data but that might change in the future. That, however, will require some internal privacy reviews and might take a long time. If that happens, all the issues and comments will be updated accordingly.
