### ISSUE TITLE
vtpm support

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#506]
Originally reported of Google Code with ID 450.

```
Xen has TPM support, and Qemu adds it from 1.5
We should model TPMs for Ganeti instances, and enable them.

Thanks,
Guido

```
Originally added on 2013-05-07 14:06:37 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Move non-critical bugs scheduled for 2.8 or 2.9 to 2.11, as in those versions only critical bug fixes will be integrated.
```
Originally added on 2013-10-30 09:48:16 +0000 UTC.

Added to Milestone: Release2.11
Removed from Milestone: Release2.9

**Comment by ge-fa** [comment]
Is anyone interested in having support for TPMs? IMHO, let's close this one as well.

new state: should be closed
