### ISSUE TITLE
Parse node group networks in the Luxi, Rapi and Simu backend

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#531]
Originally reported of Google Code with ID 475.

```
Right now, those backends don't parse the networks which are connected to node groups.

For consistency, all backends should interpret this information.
```
Originally added on 2013-05-24 08:34:02 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Move non-critical bugs scheduled for 2.8 or 2.9 to 2.11, as in those versions only critical bug fixes will be integrated.
```
Originally added on 2013-10-30 09:48:16 +0000 UTC.

Added to Milestone: Release2.11
Removed from Milestone: Release2.9

**Comment by Ganeti-Issues-Migrator** [comment]
```
Unassigning myself as I won't be able to work on this.
```
Originally added on 2014-05-20 07:57:46 +0000 UTC.

Added to Milestone: Release2.13
Removed from Milestone: Release2.11

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-05-20 07:57:59 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Removed the milestone as it's long past. As an effort to migrate all our issues to Github, I'll let someone from the community pick it up if they are interested. We'd be happy to accept patches about this.

See https://groups.google.com/forum/#!topic/ganeti/b2-eukpsXpk for more details.
```
Originally added on 2016-12-15 11:50:01 +0000 UTC.

Changed State: PatchesWelcome
Removed from Milestone: Release2.13

**Comment by ge-fa** [comment]
This issue is about: "Parse node group networks in the Luxi, Rapi and Simu backend". These information might be missing, but for now, IMHO, I would propose to close this one.

new state: should be closed
