### ISSUE TITLE
Expose watcher options via RAPI

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#535]
Originally reported of Google Code with ID 479.

```
What software version are you running? Please provide the output of "gnt-
cluster --version" and "gnt-cluster version".

2.7.0~rc1

<b>What distribution are you using?</b>
cat /etc/debian_version 
7.0

The functionality provided by `gnt-cluster watcher` is currently not exposed via the Ganeti RAPI. Having it available via this mechanism would be nice.
```
Originally added on 2013-05-30 15:41:33 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Indeed. We have plans to do so, probably in 2.10 while we rework the maintenance handling (we have some requirements for this, and a design doc will come soon)

Thanks,
Guido
```
Originally added on 2013-05-31 07:27:47 +0000 UTC.

Added Labels: Priority-High Type-Refactoring
Added to Milestone: Release2.10

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-05-31 07:27:56 +0000 UTC.

Changed State: Accepted

**Comment by Ganeti-Issues-Migrator** [comment]
```
Maintenance handling was postponed to (at least) 2.11, so implementing this functionality will be implemented then too.
```
Originally added on 2013-11-05 12:19:14 +0000 UTC.

Added Labels: Priority-Medium Type-Enhancement
Removed Labels: Priority-High Type-Refactoring
Added to Milestone: Release2.11
Removed from Milestone: Release2.10

**Comment by ge-fa** [comment]
feature: rapi

**Comment by apoikos** [comment]
I think we're missing some context as to what the original author meant. I guess we can close this issue.
