### ISSUE TITLE
please allow to config oob-ip per node

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#622]
Originally reported of Google Code with ID 566.

```
Ganeti supports to remote power-{off,on} nodes. If you want to do that over the network, you need to have some sort of mapping of the OOB IP to the node name.

It would be nice if to have the possibility to set out-of-band IPs in the config for each node. Those IPs then could be used/parsed by the oob_program.
```
Originally added on 2013-09-04 12:25:53 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-09-04 12:54:55 +0000 UTC.

Added to Milestone: Release2.11

**Comment by Ganeti-Issues-Migrator** [comment]
```
Removed the milestone as it's long past. As an effort to migrate all our issues to Github, I'll mark this as "Type-Enhancement" and let someone from the community pick it up if they are interested. We'd be happy to accept patches about this.

See https://groups.google.com/forum/#!topic/ganeti/b2-eukpsXpk for more details.
```
Originally added on 2016-12-12 14:13:41 +0000 UTC.

Added Labels: Type-Enhancement
Changed State: PatchesWelcome
Removed from Milestone: Release2.11

**Comment by ge-fa** [comment]
AFAIK, the OOB design document is more a draft than an implementation. Therefore, I would propose to close this one.

@apoikos Any opinion?

**Comment by apoikos** [comment]
I think OOB is too site-specific to implement everything in Ganeti. Rather than keeping things in the Ganeti config, I think it's much more straightforward to implement lookups in `/usr/bin/oob` which is site-specific anyway.

**Comment by ge-fa** [comment]
I agree, so lets close this one?

**Comment by iustin** [comment]
Very much agreed, indeed.
