### ISSUE TITLE
Relax fping tests during cluster-verify and on the buildbot as well

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#792]
Originally reported of Google Code with ID 736.

```
Sometimes a packet gets lost or delayed (for example due to SW network issues). In such a case fping fails even though the network is actually fine.

It'd be enough to check if one packet of a few within a few seconds returns.

```
Originally added on 2014-02-27 14:44:27 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2015-11-13 13:10:05 +0000 UTC.

**Comment by rbott** [comment]
I will close this as there is no (more?) fping involved in cluster verify, only `netutils.TcpPing()` which should be prone to single packet drops (as it leaves it down to the OS to establish a TCP connection).
