### ISSUE TITLE
Add change ability to change vg of an instance disk

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#802]
Originally reported of Google Code with ID 746.

```
Hello,

Ganeti can handle many vg, but do not allow to change VG of an existing instance disk.

Regards,
```
Originally added on 2014-03-04 10:45:32 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-03-04 11:56:27 +0000 UTC.

Added Labels: Type-Enhancement Priority-Low
Changed State: Accepted
Added to Milestone: Release2.13

**Comment by Ganeti-Issues-Migrator** [comment]
```
just want to say that as a workaround it is possible to export an instance with gnt-backup and re-import it to another vg.

i've asked for this feature in the mailling list.

here's the link:

https://groups.google.com/forum/#!topic/ganeti/GEAJiF7TZDk
```
Originally added on 2014-03-04 13:40:57 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
If this feature is accepted, would be nice to be able to throttle the move speed. When working on a production cluster, changing VG at full speed impacts greatly the performances of the other VMs.

Thanks
```
Originally added on 2014-03-05 12:18:54 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
just want to notice that it is possible to throttle data through a pipe with pv (http://www.ivarch.com/programs/pv.shtml).

pv also allows to change the rate limit of a running pv via -R switch.

just in case this feature will use console tools. pv is available on all major distros i think.
```
Originally added on 2014-08-22 09:53:12 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
This would be a complex change and currently we don't have resources for implementing it.
```
Originally added on 2015-07-29 13:41:10 +0000 UTC.

Removed Labels: Priority-Low
Changed State: PatchesWelcome
Removed from Milestone: Release2.13

**Comment by ge-fa** [comment]
feature: storage

In todays world, given all the automation etc., it might be possible to just remove and reinstall the instance. Also, an workaround exists, via `export` and `import` afterwards. Therefore, I propose to close this issue.

**Comment by apoikos** [comment]
I think this is tangential to #153 and the solution I proposed there would also work here: since LV names are using UUIDs which we require to be unique, we can rely only on the LV name to find an instance's disks. That leaves the admin with all the flexibility of moving LVs around and splitting/merging VGs.

**Comment by iustin** [comment]
@apoikos - then close this as duplicate?

**Comment by apoikos** [comment]
@iustin: I'd say yes.
