### ISSUE TITLE
devel/build_chroot uses cabal without verifying downloaded sources

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#805]
Originally reported of Google Code with ID 749.

```
The devel/build_chroot script uses cabal to build
a chroot. Cabal, however downloads and install sources
without verifying the downloaded packages against
known good hashes, or similar integrity verification.

Hence, we should add such a verification by hand.
```
Originally added on 2014-03-05 21:24:30 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-03-06 08:03:34 +0000 UTC.

Changed State: Accepted
Added to Milestone: Release2.13

**Comment by Ganeti-Issues-Migrator** [comment]
```
In Jessie we use only packages available in Debian, so it's not that important issue any more. For other distributions / deprecated versions, patches welcomed.
```
Originally added on 2015-07-29 13:36:34 +0000 UTC.

Changed State: PatchesWelcome
Removed from Milestone: Release2.13

**Comment by ge-fa** [comment]
As per the last comment: Lets close this issue?

**Comment by iustin** [comment]
More to the point, cabal now does use https, as hackage has been change to support it. So yeah, let's close.
