### ISSUE TITLE
Ganeti doesn't lint on Debian Jessie

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#858]
Originally reported of Google Code with ID 802.

```
When trying to build on Debian Jessie the build fails with

    /bin/bash: ../autotools/test-driver: No such file or directory

```
Originally added on 2014-04-16 13:30:41 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
The attached patch makes the tests compatible with the parallel-tests automake harness.
```
Originally added on 2014-04-25 14:36:24 +0000 UTC.

Attachments: 
[tests.patch](https://storage.googleapis.com/google-code-attachments/ganeti/issue-802/comment-2/tests.patch)

**Comment by Ganeti-Issues-Migrator** [comment]
```
It builds on debian jesse, see e.g., http://buildbot.ganeti.org/ganeti/builders/tests-jessie64/builds/268 However, due to the newer version of lint, lint errors remain.
I do not consider them blocking, however.
```
Originally added on 2014-06-11 08:16:42 +0000 UTC.

Added Labels: Priority-Medium
Removed Labels: Priority-High

**Comment by Ganeti-Issues-Migrator** [comment]
```
change summary to reflect updated state
```
Originally added on 2014-10-15 09:15:40 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2015-07-22 13:34:18 +0000 UTC.

**Comment by ge-fa** [comment]
This issue is dealing with Debian jessie, therefore, lets close this.
