### ISSUE TITLE
RAPI to support shutdown of all instances in cluster.

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#895]
Originally reported of Google Code with ID 839.

```
What software version are you running?
$ gnt-cluster --version
gnt-cluster (ganeti v2.10.1) 2.10.1

Today, to shutdown all instances on a cluster, an operator can use:

    gnt-instance stop --all --force-multiple --no-remember

However, no equivalent exists in the Ganeti RAPI. This issue is a request to add support to RAPI for an operation to "shutdown all instances".
```
Originally added on 2014-05-27 17:52:16 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Will be added, likely to land as:

2/instances/stop

This request should also have one request body parameter that amounts to "yes, I am sure". Otherwise, a user might just browse a cluster into torpor :)
```
Originally added on 2014-05-28 09:50:32 +0000 UTC.

Added Labels: Type-Enhancement Component-rapi
Changed State: Accepted
Added to Milestone: Release2.14

**Comment by iustin** [comment]
Closing very old issues.

Furthermore, as an API, I think this is not a good design - the latency of this call would depend linearly if not worse with the number of instances in a cluster, so it would need pagination to scale well, etc. Better done on the client side.
