### ISSUE TITLE
Add RAPI support for reading a file from a node.

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#898]
Originally reported of Google Code with ID 842.

```
$ gnt-cluster --version
gnt-cluster (ganeti v2.10.1) 2.10.1

Today, the Ganeti RAPI does not support any operation to read / get content of files from a node.

This issue requests that RAPI include support for 'gnt-cluster getfile'. For security, requests could be limited to files within a whitelist.
```
Originally added on 2014-05-27 18:14:55 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
This might be decomposed into separate requests for logs and other files.
Whitelisting is obligatory, default whitelist is empty.

```
Originally added on 2014-05-28 09:57:15 +0000 UTC.

Added Labels: Type-Enhancement Component-rapi
Changed State: Accepted
Added to Milestone: Release2.14

**Comment by ge-fa** [comment]
I would like to close this one:
- That's not the purpose of the API.
- `gnt-cluster getfile ...` doesn't exist.

**Comment by apoikos** [comment]
Agreed.

**Comment by iustin** [comment]
Totally agreed. This seems more prone to introduce security issues than solve a real problem.
