### ISSUE TITLE
gnt-cluster copyfile to accept multiple files

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#914]
Originally reported of Google Code with ID 858.

```
[ganeti 2.10.4, wheezy-backports]

Suggestion: gnt-cluster copyfile to accept multiple files listed on the command line. Improves usability.

Usage example:

gnt-cluster copyfile /etc/ganeti/snf-image/variants/*.conf /etc/ganeti/snf-image/variants.list 

```
Originally added on 2014-06-17 20:18:57 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-06-18 08:02:11 +0000 UTC.

Added Labels: Type-Enhancement Priority-Medium
Changed State: Accepted
Added to Milestone: Release2.13

**Comment by Ganeti-Issues-Migrator** [comment]
```
In the meantime, we suggest to use Parallel SSH [1] and get the list of online nodes for it from SSConf, usually located (depending on the distribution) in /var/lib/ganeti/ssconf_online_nodes.

[1] https://code.google.com/p/parallel-ssh/
```
Originally added on 2015-06-17 14:11:58 +0000 UTC.

Removed Labels: Priority-Medium
Changed State: PatchesWelcome
Added to Milestone: Unplanned
Removed from Milestone: Release2.13

**Comment by rbott** [comment]
I will move forward here and close this feature request as there has not been any activity on this issue.
