### ISSUE TITLE
Supplement/generate proper 'shrink' functions in 'Arbitrary' instances

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#929]
Originally reported of Google Code with ID 873.

```
This will allow QuickCheck to produce more meaningful and simpler counter-examples for failed tests.

See http://stackoverflow.com/q/16968549/1333025 and http://hackage.haskell.org/package/QuickCheck-2.7.5/docs/Test-QuickCheck-Arbitrary.html#v:shrink
```
Originally added on 2014-07-07 07:43:42 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
2.12 is already released and 2.13 close to cut. Hence, postponing
as it is a feature request, not a bug.
```
Originally added on 2014-10-13 12:15:35 +0000 UTC.

Added to Milestone: Release2.14
Removed from Milestone: Release2.12

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2015-04-15 11:44:30 +0000 UTC.

Added to Milestone: Unplanned
Removed from Milestone: Release2.14

**Comment by iustin** [comment]
Closing very old issues. This is also a very generic request, and hard to scope. Let's file individual bugs when specific instances are found to be defficient.
