### ISSUE TITLE
devel/build_chroot testing

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#964]
Originally reported of Google Code with ID 908.

```
The build_chroot script often fails when new dependencies are introduced, and given that we recommend this script to newcomers to Ganeti, we should maintain a greater standard of quality for it.

A daily test on the public buildbot should be made.
```
Originally added on 2014-08-04 14:52:02 +0000 UTC.

**Comment by rbott** [comment]
I will close this now as the script is unmaintaned/unused and in general build chroots have probably been superseeded by Docker environments (e.g. these images: https://github.com/ganeti/ci-images)
