### ISSUE TITLE
Add MARS support

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#967]
Originally reported of Google Code with ID 911.

```
Hi,

there's a new distributed storage system called MARS[1] that looks very promising and has some advantages over DRBD[2]. It would be cool to have support for it.

[1] https://github.com/schoebel/mars
[2] http://www.linuxtag.org/2014/de/programm/vortragsdetails/?eventid=2308
```
Originally added on 2014-08-05 08:44:44 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-08-05 08:54:28 +0000 UTC.

Added Labels: Type-Enhancement Priority-Low
Changed State: Accepted
Added to Milestone: Release2.13

**Comment by Ganeti-Issues-Migrator** [comment]
```
While MARS certainly seems interesting, I do not believe it to be a good replacement for DRBD in Ganeti right now due to its overhead (large transaction logs) and the fact that its primary use is long-distance replication.

There is also the question of whether it is wise to have georeplication present on the Ganeti level or if it is better done on the storage level, with extra information provided by Ganeti.

Anyway, if someone sends a design / patches, we will gladly look at them, but we very likely will not do this ourselves :)
```
Originally added on 2014-08-05 12:12:13 +0000 UTC.

Removed from Milestone: Release2.13

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2015-06-03 13:30:50 +0000 UTC.

Removed Labels: Priority-Low
Changed State: PatchesWelcome
Added to Milestone: Unplanned

**Comment by rbott** [comment]
MARS does not seem have caught on / gained enough traction in the past years. I will close this feature request for now and we can always reconsider if more people are interested.
